### ISSUE TITLE
[Bug] Selection in GraphQL autocomplete list is reset to the first item when scrolling by arrows

### ISSUE THREAD

**Issue by 4ekki** [Kong/insomnia#1015]
- Insomnia Version: 5.16.6
- Operating System: Win10

## Details
[Bug] Selection in GraphQL autocomplete list is reset to the first item when scrolling by arrows

S2R: 
1. Create new request with GraphQL type and set address to http://try.sangria-graphql.org/graphql 
2. Type in 'query {}'
3. Press [Ctrl]+[Space] to get autocompletion list 
4. Press [Arrow down] button several times

As a result, on #4 selection is reverted to the first item in the list. 

On this gif, I press [Arrow down] twice to select '__schema' item. After that, 'human' item becomes selected automatically. 
![gif](https://user-images.githubusercontent.com/38757986/41994701-fb3b4932-7a57-11e8-973d-31b570823ca2.gif)

**Comment by gschier** [comment]
Hmm, that's odd. Going to take a look now

**Comment by gschier** [comment]
Hmm, I can't seem to reproduce this issue (on Mac). Can you describe more details around when it happens? Is it after a delay, always on the 3rd item, etc? What if the autocomplete list is longer?

**Comment by 4ekki** [comment]
Reproduces every time on my machine, doesn't depend on list length or the exact final position. 
Also, I've reproduced it with scrolling the list by mousewheel, you just need a bit longer list for the scrollbar appear.

**Comment by gschier** [comment]
So it always happens on the 3rd item?

**Comment by 4ekki** [comment]
No, it doesn't depend on the final position, can happen on 2nd or 5th, doesn't matter. But looks like it happens after the same time interval, ~1sec after opening the list.

**Comment by 4ekki** [comment]
This one is still actual in 6.0.2

**Comment by gschier** [comment]
I was never able to reproduce it, unfortunately. Perhaps someone who is experiencing the problem wants to take a shot at fixing (or at least debugging) it?

**Comment by rafaelrenanpacheco** [comment]
I use Insomnia with Arch Linux and Gnome as DE, and for a long time I see this bug in the GraphQL autocomplete dropdown.

**Comment by nicholaslythall** [comment]
Confirming this is still an issue in 7.1.1 on macOS Catalina 10.15.3

**Comment by nickwinsor** [comment]
+1 on this. 
I experience this issue hundreds of times a day. 

One thing to add though is that letting the autocomplete dropdown sit for a second before navigating, bypasses the bug.

**Version: Insomnia Core 2020.4.1
Release date: 9/22/2020
OS: Darwin x64 18.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0**

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by develohpanda** [comment]
Closed by #3468
