### ISSUE TITLE
[Feature Request] Add support for SOCKS proxy

### ISSUE THREAD

**Issue by kaoet** [Kong/insomnia#1085]
Support for sock4/socks5 proxy.

**Comment by gschier** [comment]
Does SOCKS not work with the current proxy setting?

**Comment by gschier** [comment]
Note: Insomnia uses curl to send requests to if curl supports is then it should be possible

**Comment by gschier** [comment]
Note: Insomnia uses curl to send requests to if curl supports is then it should be possible

**Comment by kaoet** [comment]
I found only HTTP proxy in the perference GUI.

curl support socks5, just use:
```
all_proxy=sock5h://localhost:1080 curl -v www.google.com
```

**Comment by gschier** [comment]
Looks like socks4 aed socks5 are supported https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

Did you get it working?

**Comment by kaoet** [comment]
I can't even find a GUI option to specify socks proxy in insomnia. I can only see "HTTP Network Proxy" in Application -> Preferences -> General. And there is nothing like "SOCKS Network Proxy" there.
I'm using Insomnia v6.0.1 on debian buster/sid.

**Comment by gschier** [comment]
That's what I meant. You should be able to put your socks url in there if curl supports it

**Comment by kjstouffer** [comment]
Correct me if I'm wrong, but it appears that the HTTP section will route only http traffic through the proxy, and HTTPS section will only route https traffic. So if i wanted to route both HTTPS and HTTP traffic, i would need to set both fields to the socks proxy, like this: 
![image](https://user-images.githubusercontent.com/9042425/44669156-2cdfae00-a9ed-11e8-8895-f022408194b5.png)

Perhaps a UI change could help explain that any of the proxy options here would work: https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html. Something like a tooltip next to each of the proxy parameters or a link to documentation about supported proxy types would be helpful.

**Comment by gschier** [comment]
I _think_ that should work. I can't actually remember why I split the config up into HTTP/HTTPS. Probably because that's the way Paw or Postman did it or because MacOS splits the proxy configuration in that way as well.

So did that configuration work for you? I can update the tooltip help text if so.

**Comment by Fgruntjes** [comment]
Just for reference the suggested config worked.
![screenshot 2018-10-24 at 15 50 52](https://user-images.githubusercontent.com/984466/47435310-a0f7c180-d7a4-11e8-9792-1668bd0263b3.png)

**Comment by socheatsok78** [comment]
> Just for reference the suggested config worked.
> ![screenshot 2018-10-24 at 15 50 52](https://user-images.githubusercontent.com/984466/47435310-a0f7c180-d7a4-11e8-9792-1668bd0263b3.png)

What are the different between `socks5` and `socks5h`? Apology a little bit off-topic!

**Comment by xpac1985** [comment]
> What are the different between `socks5` and `socks5h`? Apology a little bit off-topic!

socks5h = The name of the server you want to connect to is resolved (DNS) by the proxy
socks5 = The name of the server you want to connect to is resolved by your local device

**Comment by socheatsok78** [comment]
Thank you @xpac1985

**Comment by dimitropoulos** [comment]
reopening because, as far as I can tell, we didn't want the stalebot to close it (we've since removed the stalebot altogether because of similar problems)

**Comment by kjstouffer** [comment]
hi @dimitropoulos 👋 , I believe this issue is resolved: insomnia supports socks5 proxies via the methods described above: https://github.com/Kong/insomnia/issues/1085#issuecomment-432664923

**Comment by dimitropoulos** [comment]
ahh, gotcha.  thanks!

**Comment by walquiriosaraiva** [comment]
a melhor solução é usar socks5h://localhost:8080 
no meu caso funcionou que foi uma blz. Obrigado pessoal pela ajuda. Deus abençoe vocês.

**Comment by sir-farfan** [comment]
They should really add this to the documentation.
