### ISSUE TITLE
[Feature Request] Add WSDL-SOAP support

### ISSUE THREAD

**Issue by hadisfr** [Kong/insomnia#1103]
Even though WSDL-SOAP API standard is getting old and is being widely replaced by JSON, but there are still some old working WSDL-SOAP-based APIs.

It may be a good idea to add some special support for them, like what [SmartBear/soapui](https://github.com/SmartBear/soapui) or postman are offering.

Ref: [SoapUI SOAP Testing](https://www.soapui.org/rest-testing/getting-started.html)

**Comment by gschier** [comment]
What is the bare minimum needed to support SOAP? Insomnia already supports XML requests.

I don't think Postman supports SOAP. It looks like the docs just tell you to make an XML request manually. Maybe I'm missing something? http://blog.getpostman.com/2014/08/22/making-soap-requests-using-postman/

**Comment by hadisfr** [comment]
I've expected auto-creating SOAP request templates based on a WSDL file for every supported method of API.

I think so. I meant something like SoapUI or, if it's not possible, adding something like what Postman has got to documentations of Insomnia.

**Comment by boumboum** [comment]
+1 for this.
All the time I have to test a SOAP service I have to write a client which access' to that server.
I can test my APIs but not my SOAP services.
The enterprise world is still actively relying on SOAP.
So there is definitely a need for this

**Comment by verglor** [comment]
Hi @gschier, could you consider accepting this issue ? Maybe it can be renamed to "WSDL import".

It would be really useful to be able to import wsdl file so we can use Insomnia instead of SoapUI with it's ugly UI.

**Comment by Diaskhan** [comment]
There is Mature Soap lib for nodejs
https://github.com/vpulim/node-soap

**Comment by Diaskhan** [comment]
There some Ideas or Prototype interface Of Soap Client ?
UI sketchs?
Conception ?

**Comment by JSamir** [comment]
I would like to have this feature too (import request templates from WSDL). I can also confirm that in the enterprise world SOAP ist still very much alive. Unfortunately I cannot contribute to the implementation.

A workaround I currently use is to generate request templates in SoapUI and then copy/paste them (one by one...) to Insomnia.

**Comment by iseehk** [comment]
+1

**Comment by ctaylor-c172** [comment]
+1 for this

SOAP and XML is so common in enterprise systems.

**Comment by liltenou** [comment]
+1 I need this. SOAP is very common in enterprise systems. I work as a consultant and big name businesses still leverage this technology and implement new API daily.

**Comment by Toumash** [comment]
Work in progress. Currently, the importer converts the data (the jest tests as an evidence) but it wont run as a whole electron app. Im getting an error in the import modal dialog

> TypeError: result.summary[_models__WEBPACK_IMPORTED_MODULE_11__.workspace.type] is not iterable

[**my work is here**](https://github.com/Toumash/insomnia/tree/feature/wsdl-importer)

**Comment by artemy-osipov** [comment]
#1675 is it a completed solution or intermediate solution?
In the latter case, I think it's worth reopening issue as in version 7.0.6 and develop branch (at macos) error still occurred while import WSDL
```
TypeError: result.summary[models__WEBPACK_IMPORTED_MODULE_11_.workspace.type] is not iterable
```

Original cause throw from `apiconnect-wsdl`  by method `getJsonForWSDL(wsdl)`

```
Error: ENOENT, renderer/files/XMLSchema.xsd not found in /Users/some/GITHUB/insomnia/packages/insomnia-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar
    at notFoundError (ELECTRON_ASAR.js:108)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:571)
    at getArchive (parse.js?59a5:793)
```

**Comment by artemy-osipov** [comment]
@gschier The error disappeared after adding the `insomnia-importers` dependency into externals at `webpack.config.base.babel.js` for `insomnia-app` package (dirty hack). Unfortunately, wsdl import does not work if the scheme has external links to xsd
```
Error: Failed to find the file commonTypes.xsd in the zip archive. The file is referenced in file internal.wsdl. Ensure that the file is packaged in the zip file.
    at Object.Error (/Users/some/GITHUB/insomnia/packages/insomnia-importers/node_modules/apiconnect-wsdl/lib/strong-globalize-fake.js:31)
    at expandOneSchemaImport (/Users/some/GITHUB/insomnia/packages/insomnia-importers/node_modules/apiconnect-wsdl/lib/postParse.js:483)
    at expandSchemaImports (/Users/some/GITHUB/insomnia/packages/insomnia-importers/node_modules/apiconnect-wsdl/lib/postParse.js:520)
    at checkForSchemaImports (/Users/some/GITHUB/insomnia/packages/insomnia-importers/node_modules/apiconnect-wsdl/lib/postParse.js:546)
    at checkOneWSDLImport (/Users/some/GITHUB/insomnia/packages/insomnia-importers/node_modules/apiconnect-wsdl/lib/postParse.js:271)
    at process._tickCallback (internal/process/next_tick.js:68)
```

**Comment by shaneparsons** [comment]
I'm also confused as to whether this has been published or not, and how to use it if it has? Can this please be documented somewhere?

**Comment by Toumash** [comment]
> I'm also confused as to whether this has been published or not, and how to use it if it has? Can this please be documented somewhere?

I believe if it has been merged into develop, then it would show up in the next release, but i'm not sure

**Comment by JDonaghy** [comment]
I'm really looking forward to using this feature, but it does not seem to be available and working. Since .wsdl is listed as a valid import extension, I tried to import [this WSDL file](https://www.w3schools.com/xml/tempconvert.asmx?WSDL) using Insomnia Version 2020.2.2 and I get the following error: Error: No importers found for file.
Is it just not in the release branch yet?

**Comment by o-az** [comment]
Any idea if this feature will ever become available?

**Comment by eliam** [comment]
Same.  v2020.4.2.  Includes .wsdl file type for the import but bugs out with "Error: No importers found for file".

Any chance of reopening this feature request?  I'd still find this handy.

**Comment by BalintPogatsa** [comment]
+1

**Comment by baermathias** [comment]
I am using the version `Insomnia Core 2020.5.1` and what works is the import from for **some** wsdl urls/files, but not all (e.g. this one works in SOAP UI, but not Insomnia http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL) and also there is the problem, that the imported methods don't work at all (but they do work in SOAP UI)
So please reopen this issue @gschier
