### ISSUE TITLE
[Feature Request] Allow bulk edit for query params

### ISSUE THREAD

**Issue by 6utt3rfly** [Kong/insomnia#1110]
The `Header` tab has a `Bulk Edit` button that lets you quickly edit multiple parameters and makes it easy to copy parameters between routes. The `Import from Url` is useful, but in some cases it would be nicer to copy and paste parameters between endpoints using the existing bulk editor rather than doing so by url. Can we have the `Bulk Edit` button and functionality copied to the `Query` tab?

Insomnia v6.0.2

**Comment by 4n70w4** [comment]
+1

**Comment by tostringtheory** [comment]
@gschier - I wanted to pick this one up.  Any preference on implementation in the bulk editor?  Was looking to basically use similar functionality as the header editor.  I wasn't sure however if the name/value functionality should be done like headers with `name: value` or follow more general with query parameter formatting such as `name=value` on each line.  Any other thoughts are welcome too.

**Comment by gschier** [comment]
I think it should be the same as the header editor with regards to how it works. But, I think the format for the text being edited should be a raw query string `a=b&c=d&e=f`. That way users can copy/paste query strings into it and have it work.

**Comment by 4n70w4** [comment]
`a=b&c=d&e=f ` format would not be convenient for large arguments.
It will be good to additionally allow to enter edit line by line.

**Comment by jalius** [comment]
bulk editing for FormURL encoded body would make sense as well

**Comment by Surendrajat** [comment]
I got a strong use-case for this one. I want to trigger a `Jenkins` job with around 30 params copied from the last job. Typing those params manually one by one will take forever and then have to move back to `PostMan` since it's got the `bulk-edit` function for queries. Hope somebody will take this task for implementation.

**Comment by stevebaros** [comment]
I have a usecase for this , cant typeaway 50 colums comma separated . back to postman.
