### ISSUE TITLE
[Feature Request] [Minor] Copy timeline output as HTML

### ISSUE THREAD

**Issue by coolhome** [Kong/insomnia#1117]
I think having the ability to copy the curl timeline output as HTML would be beneficial when using chat clients like Microsoft Teams. This feature would bring the color highlighting with it. If implemented it should probably be a preference.

**Comment by gschier** [comment]
I think it's fine to enable rich copy by default. You can always use Cmd+Shift+V (or Windows/Linux alternative) to paste unformatted if needed.
