### ISSUE TITLE
[Feature Request] Don't clear Preview when Response Filter is invalid/non-existent 

### ISSUE THREAD

**Issue by yozlet** [Kong/insomnia#1259]
Following on from #1258:

Short version: Only update the Response Preview when the Response Filter evaluation returns something worth showing.

In more detail:

* *Given:* the Preview pane is displaying any response content
* *When:* the Response Filter input changes
* *And:* the Response Filter input evaluates as either syntactically invalid or non-existent in the current document
* *Then:* don't update the Preview to show `[]` or similar, as it hides the document tree that the user is currently trying to navigate.

Example: If I'm trying to filter down to `$.store.books[*].author`, then as soon as I type `$.` the Preview just shows `[]`, and I won't see anything useful until I either delete or type as far as `$.store` . This is particularly annoying if I'm continually looking at the Preview as a guide to the path I'm typing.

**Comment by gschier** [comment]
Hmm, I think the suggestion could possibly be confusing as well in the current state, but would probably be fine if #1258 were first implemented. That way the user would still see visual feedback, even though the editor contents did not change.

**Comment by yozlet** [comment]
@gschier Can this one be reopened? Sure, it's been a long time, but it's still a valid enhancement.

**Comment by gschier** [comment]
Yep, sorry. Have been having some trouble with stalebot lately
