### ISSUE TITLE
 [Feature Request] SSE/EventStream debuging

### ISSUE THREAD

**Issue by TareqK** [Kong/insomnia#1345]
Can we look into adding an EventStream client? it would be really helpful to debug SSEs and they are really starting to take off.

**Comment by TareqK** [comment]
See(Server Sent Events)  is a way for servers to push notifications to
clients (without websockets or the clients polling the server). It's based
on the older idea of http streaming, except it's more refined and involves
less hacking. Here is a short how to on both the client and server side
from MDN


https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

**Comment by Simorenarium** [comment]
This is still interesting.

**Comment by TareqK** [comment]
Any interest in this anymore?

**Comment by ImVexed** [comment]
Still interested

**Comment by jonataslaw** [comment]
Because this is closed?

**Comment by thedomeffm** [comment]
+1

**Comment by ThaDaVos** [comment]
Any progress on this?
The same seems to be asked for Postman but like this issue - went quiet...
https://github.com/postmanlabs/postman-app-support/issues/6682

**Comment by BrakefieldMN** [comment]
This is still interesting.

**Comment by matttrawicki** [comment]
👍

**Comment by bob-laz** [comment]
+1

**Comment by noorulrazvi-saal** [comment]
Any update on this?

**Comment by loeffel-io** [comment]
+1000

**Comment by GCSBOSS** [comment]
Need this ❤️

**Comment by itxtoledo** [comment]
up

**Comment by softmarshmallow** [comment]
Insomnia has a better UI/UX and usability but i have to switch between hopscotch for websockets & sse. quite annoying.

Can we get at least an ETA?

**Comment by sathyarajagopal** [comment]
+1
