### ISSUE TITLE
Add better support for fileuploads to graphQL

### ISSUE THREAD

**Issue by alexbjorlig** [Kong/insomnia#1363]
- Insomnia Version: 6.3.2
- Operating System: macOS Mojave 10.14.2

## Feature Request
Currently it's possible to upload files to GraphQL using Insomnia by sending a POST Multipart request, following the [graphql-multipart-request-spec](https://github.com/jaydenseric/graphql-multipart-request-spec). 

But it would be awesome if you could do this using a file picker in Insomnia.

I followed the GraphQL file upload implementation described [here](https://blog.apollographql.com/file-uploads-with-apollo-server-2-0-5db2f3f60675).

**Comment by dauledk** [comment]
Now there is event a place to look for inspiration 😄  https://sirmuel.design/working-with-file-uploads-using-altair-graphql-d2f86dc8261f

**Comment by NikxDa** [comment]
Still relevant.

**Comment by kaitlynbrown** [comment]
Bad bot. Please re-open.

**Comment by calvera** [comment]
examples here https://github.com/jaydenseric/graphql-multipart-request-spec

**Comment by NikxDa** [comment]
@gschier Could you please reopen this? It doesn't get the attention it deserves.

**Comment by heruan** [comment]
@gschier Can this be reopened, please?

**Comment by kaitlynbrown** [comment]
I believe usage of `multipart/form-data` is already part of the graphql spec: https://github.com/jaydenseric/graphql-multipart-request-spec
At the very least, Apollo Server makes use of this spec for handling graphql file uploads

**Comment by mxmlnglt** [comment]
@dauledk @gschier is there a way this issue can be re-opened? I'd also need this feature to easily test file uploads on a GraphQL endpoint... Thanks!

**Comment by semoal** [comment]
We could add this to the next 6 months iteration plan? I could work on it

**Comment by adelbke** [comment]
Is there a way I can contribute to the implementation of this feature?

**Comment by warent** [comment]
Would love to see this. Using curl in the meantime

**Comment by hongbo-miao** [comment]
It would be great to have something like this Altair GraphQL Client. Thanks!

![image](https://user-images.githubusercontent.com/3375461/104857872-569b2600-5956-11eb-82a8-a84b01c37797.png)
