### ISSUE TITLE
[Bug] Hangs on moving a request to a folder

### ISSUE THREAD

**Issue by mertvetsky** [Kong/insomnia#1373]
- Insomnia Version: 6.32
- Operating System: Arch Linux 4.20.5, Xfce/Xfwm

## Details

On moving any request to any folder app fully hangs.
It may depends on electron 3.* bug: https://github.com/electron/electron/issues/14430

**Comment by gschier** [comment]
That's really strange. It doesn't seem to happen on my end (Mac). Maybe an Electron update will fix it?

**Comment by mertvetsky** [comment]
Yeah, this may solve problem. If needs, I can try build with next Electron, but if updating already in your nearest plans, I'll just waiting.

Btw, in other linux distros (like Ubuntu/Mint) problem doesn't appear.

**Comment by gschier** [comment]
So I think the only way forward on this one is to wait for Electron to fix it. There might be a fix in 4.x already but there were some build issues caused by the upgrade and I didn't have the time to spend to fix it. I'll try and get an upgrade into the next release though.

**Comment by nkkollaw** [comment]
@gschier : are you able to reproduce the problem?

**Comment by gschier** [comment]
I haven't been able to reproduce it no. Perhaps it depends on something external to the application like mouse/monitor/etc settings?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nkkollaw** [comment]
No idea, but I doubt it. The same thing happened in VS Code, and they fixed it (I guess by upgrading Electron). 

This is most probably the bug in Electron that it's causing the crash: https://github.com/electron/electron/issues/12820/

Unfortunately I have no idea how Electron apps work or I'd create a pull request. I'm just here to complain :-D

**Comment by gschier** [comment]
😢

**Comment by nkkollaw** [comment]
Mh..?

**Comment by gschier** [comment]
Just shedding a tear because bugs like this are so difficult 🙃

**Comment by nkkollaw** [comment]
HA!
Actually, it's even worse now. Now it's working :-/

I have no idea. Maybe it's related to memory usage..? For instance, if I'm low in memory it doesn't work..?

Baffling.

**Comment by mertvetsky** [comment]
Seems to be fixed by updating xfce to 4.14 (with gtk3)

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

However, it looks like this could be resolved now? Let us know if we should reopen.
