### ISSUE TITLE
[Feature Request] Add .http request format import 

### ISSUE THREAD

**Issue by rustamwin** [Kong/insomnia#1384]
- Insomnia Version: latest
- Operating System: Debian Stretch

## Details

Support for WebStorm HTTP request collection

**Comment by gschier** [comment]
Feel free to submit a PR for this if you'd like to the internal 
`insomnia-importers` package

https://github.com/getinsomnia/insomnia/tree/develop/packages/insomnia-importers

**Comment by KarthikSiddarth** [comment]
I am taking this

**Comment by rustamwin** [comment]
Hi @KarthikSiddarth 
Any news on this?

**Comment by KarthikSiddarth** [comment]
> Hi @KarthikSiddarth
> Any news on this?

started working on it, will update soon
