### ISSUE TITLE
[Feature Request] OAuth 2 missing Identity token.

### ISSUE THREAD

**Issue by mim-Armand** [Kong/insomnia#1423]
- Insomnia Version: `6.2.3`
- Operating System: Mac OSX

## Details

OAuth specification document provides two kinds of token, `access` token and `identity` token, The **Insomnia** OAuth 2 module works beautifully for most of the things as it exposes and uses the `Access_token` (in addition to `refresh_token`) which is used more often, there are a few oddballs however that need `identity_token` for certain calls, like **AWS Cognito** User pool integration with **API Gateway**:

To authenticate requests to API-Gateway endpoints that are protected by AWS Cognito **Authorizers**, the `access_token` will not work! but the `identity_token` which is included in the same response body that provides the `access_token` works! ( although access_token works to make calls to Cognito endpoints itself!! but anyways! )

I think it would be great if we provide this functionality as AWS is a big player and this will come handy in a lot of use-cases, especially since there aren't any other alternative clients, currently, supporting this ( Postman does not have this feature either ), this will be very useful for developers/engineers working in a serverless stack!

Thanks,
- mim

**Comment by mim-Armand** [comment]
As I was talking with @gschier , I have made a few changes to the source code of the OAuth2 module and rebuild the project to see if it's working, and it does work nicely! as a matter of fact, OAuth2 module receives the `identity_token` at the same time as `access_token` and `refresh_token`, it doesn't show it however in the UI ( it's simply ignored for OAuth protocol ), which may make sense in most of the use-cases but in the few that it's needed, having it could be very useful.

Now that I've verified that it works, I'm thinking to make a **PR**, later on, to let the user choose which of the two tokens s/he wants to use. something like a toggle-button or similar that let the user switch between the two functions.. in my current modification, I simply render the token on the UI in an additional text-field above the `access token` field.

If anybody's interested in such a feature I'll be happy to work on it, just let me know!

Best,
- mim

**Comment by gschier** [comment]
I think some sort of toggle would work but only show it if both are detected 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mim-Armand** [comment]
That's a good idea!

**Comment by antempus** [comment]
Any update on this, I have a defined workflow that uses the ID token and having access to it is required.

**Comment by mim-Armand** [comment]
@antempus I'm hoping to make a **PR** this week or early next week, but if you need a hacky solution, for now, feel free to build the Master branch on my [fork](https://github.com/mim-Armand/insomnia).
My main blocker is to learn the proper way of contributing to the project ( learning the project structure, tests, etc ), but I'll try to spend some time this week to get it done as I'd really love to contribute.

**Comment by mim-Armand** [comment]
So the least intrusive solution I can think of is to add a checkbox in the UI that lets the user choose `identity_token` instead of `access_token` when it's available and desired. ( like in the screen-shot below )

I have implemented the UI to show the token if it exists in the response, we need to let the user choose which token to use though to make their calls, or we can add that in a future PR?

I still also need to check and add tests if needed

@gschier does that sound good?

<img width="622" alt="Screen Shot 2019-05-22 at 12 15 36 PM" src="https://user-images.githubusercontent.com/1734237/58194663-c477e180-7c8b-11e9-9540-9e7ed540e7de.png">

**Comment by antempus** [comment]
@gschier what would be needed to help get @mim-Armand's improvement into the main codebase?

**Comment by gertcominotto** [comment]
@mim-Armand @gschier can this still be implemented? This is holding me back (and my team) to switch to Insomnia.

**Comment by mim-Armand** [comment]
@gertcominotto It definitely can, but my Fork is pretty out-dated now and needs to be re-worked and I didn't hear anything back from the team behind Insomnia either so IDK really if they'd be open to it :/
I built the tool from my fork back when I needed this feature.

**Comment by savanvadalia** [comment]
Any updates on this feature seems like very useful missing feature, I am in the same situation using AWS cognito as the OAuth provider and want to use the IdToken. Even Postman doesn't support this so will give an added advantage to Insomnia. Really surprised this request was Closed.

@mim-Armand , any way community can use your work?
Is there way your tool can be shared?

@gschier, any chance we can reopen this issue?

**Comment by mim-Armand** [comment]
@savanvadalia you are welcome to build this fork [here](https://github.com/mim-Armand/insomnia/tree/master) which has that feature implemented (as in the picture above) but it's behind upstream for all the other updates that may have happened during the last two years.
I think we can bring it back/up to date though if we can get it merged?

**Comment by savanvadalia** [comment]
@mim-Armand , thanks for your prompt reply. I had a look at your commit, sorry I didn't realize I would need front-end development skills (Javascript. React, etc) to contribute. I am terrible with frontend 😞  so I guess I can just add my voice here to reopen the issue.

**Comment by alanwill** [comment]
How can we get this issue re-opened? Just reading the comments here it seems there's a fair amount of interest in this feature, myself included

**Comment by develohpanda** [comment]
Hey folks, sorry about the lack of communication! 🤗 I'll re-open this issue because it was closed by stale bot and without good reason. @mim-Armand / @alanwill please feel free to raise a PR and we can work towards getting this into the project.

Happy to help in case you need any guidance with UI and testing (where possible).

**Comment by doronguttman** [comment]
if you got here by searching for a solution, like me, apparently Insomnia now supports this in an undocumented (at least none that I could find, except for #3211) way:
1. configure OAuth2 as usual
2. make sure to request a scope which provides the relevant token
3. go to the `Headers` tab
4. Add `Authorization` header, where value is:
   - for `id_token`: `Bearer {% request 'oauth2-identity', '', 0 %}`
   - for `refresh_token`: `Bearer {% request 'oauth2-refresh', '', 0 %}`

![image](https://user-images.githubusercontent.com/8771525/215190055-dd3e3e23-ab9c-41ba-99b4-d143d18145ce.png)
