### ISSUE TITLE
[Feature Request] Allow prompt values to be cleared

### ISSUE THREAD

**Issue by scottmmmm** [Kong/insomnia#1456]
- Insomnia Version: 6.4.1
- Operating System: Ubuntu 16.04 LTS

## Details

The Prompt tag is a really useful way of getting a user to provide a piece of data that can't be derived from a previous request. 

It'd be good if the user could choose to clear the value stored against a Prompt Tag. As it stands, there only seem to be two ways of doing this :

1. Close the application and restart it.
2. Change the Storage Key (the help tooltip even suggests this, but it's not a very nice way to do it).

## Use Case
I want to use the prompts at the start of a series of chained requests which make up a typical usage scenario. E.g. my API allows a user to navigate through a document page by page via multiple requests. At the start of my chain I want to provide the ID of the document to be traversed in a prompt.

I want the same document ID to be used on every request in the chain as I work my way through the document. Once I've finished I need to be able to execute the scenario again - sometimes with a different document ID, sometimes with the same one!

At the moment I'd have to either restart the tool at the end of the chain, or edit the Prompt Tag and change the Storage Key to achieve a "re-prompt".

## Solution ideas
Perhaps the "Edit Tag" screen could have a "Clear value" button on it somewhere? Or maybe there could be some other way of clearing these stored values.

**Comment by gschier** [comment]
That's a neat use case. Right now the plugin system doesn't have a way for template tags to define actions but I'll give it some thought and see how that might work within the current system.

I'm not sure if this is any easier, but you could define the storage key inside an environment variable (if you're not doing that already) and reference that within each Prompt tag. Then at least you only have to update it in one place.

**Comment by scottmmmm** [comment]
Thanks, I'll give that a shot to see if it's easier.

**Comment by gliviu** [comment]
I have a similar usecase. I generate a random value during request  then I want to reference that value from following requests.
I think it would be great if we could have a plugin similar to  'Response - reference values from other request's response' but for requests.

**Comment by scottmmmm** [comment]
I still think this is a problem with using the prompt tag.

**Comment by gschier** [comment]
Ya, I think this is still worth doing too. 

We could maybe have a way to define "action" buttons on a template tag that will call a callback in the plugin definition. Once we add support for this to the plugin API and tag editor, we could update the prompt plugin to include a "clear" action.

```js
module.exports.templateTags = [{
    name: 'example',
    displayName: 'Button Example',
    actions: [
        {
           name: 'Test Button',
           run() {
               console.log('Button was clicked');
           }
        }
    ],
    args: [
        {
            displayName: 'Example Text Field',
            type: 'string'
        }
    ],
    async run (context, exampleTextField) {
        return exampleTextField;
    }
}];
```

**Comment by relgames** [comment]
Hi, this would be a nice feature indeed. 
`1. Close the application and restart it` is not working - after restart the variable is still having a value, so it does not prompt for it.

We use paid Teams feature so changing the storage key is not convenient as it would affect 10 members of the team. 

We need a way to clear the key and force the prompt.

**Comment by relgames** [comment]
@gschier Hi, I typed my password into a prompt variable. My password is now changed because it expired. 

How do I force Insomnia to re-ask the password? 
Closing and opening again does not help.

**Comment by vitorhugods** [comment]
@relgames I'm facing the exact same issue with one password. Did you find any work-around?

**Comment by relgames** [comment]
@vitorhugods no :(  I made a second variable.

**Comment by elemanhillary** [comment]
it would be better to provide screen shots, it would really help us locate the UI components by searching for text they hold and know why to start from, i feel this feature but i dont have an idea where to start from

**Comment by vitorhugods** [comment]
@elemanhillary Here's an example.

![grafik](https://user-images.githubusercontent.com/9389043/68784896-99b88580-063d-11ea-9466-ceb4689d5ba9.png)


I think the idea is to clear the storage `value`. So a button between the `key` and the cog icon to clear it would be great.

Perhaps even to actually see the current value of the key. Because there's no way to see it in the app right now.

**Comment by scottmmmm** [comment]
![insomnia-prompt](https://user-images.githubusercontent.com/3959288/68786237-53f8be80-0637-11ea-831f-ed427241589f.png)

Yeah @vitorhugods , you see that live preview when you hover over the prompt in the URL bar (as shown in the image, thougn my cursor is missing for some reason).

It'd be really good if you could just right click the coloured Prompt box to select the "clear" option, but I don't see any other precedent for something like that - so clicking on the Prompt to open the full Edit tag screen is probably the best place to start.

**Comment by elemanhillary** [comment]
@vitorhugods by tomorrow evening i will raise a PR for that thanks. let me bookmark this  to remind me

**Comment by elemanhillary** [comment]
@vitorhugods  and @scottmmmm  what if i put the clear button in the gear next to storage key

**Comment by vitorhugods** [comment]
@elemanhillary I see no problem with that. Seems good, and in a good predictable place, as @scottmmmm reinforced. I'm no contributor to this project (yet), so I don't feel like I have a huge say in this.

**Comment by vitorhugods** [comment]
There's still one thing not addressed, as stated by @relgames:

> 1. Close the application and restart it is not working - after restart the variable is still having a value, so it does not prompt for it.

_At least_ the text message suggesting to re-open Insomnia should be removed and changed, providing information to the user on how to clear the value using the new button.

**Comment by gschier** [comment]
Restarting the app will not clear the prompt storage because it is persisted in the local database. Currently, the only way to clear the value is with the storage key. 

@elemanhillary, I think the best place for it would be to add it as an extra row in the Edit Tag form. That would be the easiest to do and it would be the most flexible API for other plugins to use if they want to add their own action buttons as well.
