### ISSUE TITLE
[Feature Request] Black background when using dark themes

### ISSUE THREAD

**Issue by ivanwhm** [Kong/insomnia#1477]
- Insomnia Version: 6.4.2
- Operating System: Windows 10

## Details

Hi Guys!

I'm using Insomnia with a dark theme, however, every time that I openned Insomnia, I get a white background color screen while Insomnia is loading the application. Is it possible to change that background color from white to a dark color, maibe related to the theme I choose?

![Opening](https://user-images.githubusercontent.com/371218/57074453-4642a380-6cba-11e9-9f78-d29fa1c35ceb.png)

**Comment by gschier** [comment]
I took a brief look at how hard this would be to do and it's a bit trickier than I expected. Going to leave this one open for a later time.

**Comment by KarthikSiddarth** [comment]
Can I take this?
