### ISSUE TITLE
[Improvement] Allow for unnamed requests and display the url as the name

### ISSUE THREAD

**Issue by bgmort** [Kong/insomnia#1505]
- Insomnia Version: 6.5.1
- Operating System: macOS 10.14.3

## Details

Every time I create a new request from scratch or by duplicating an existing request, I have to create a name for it.  Most of the time I'd rather that the name displayed in the sidebar just be the url or the request.  It requires an extra step to create the request, and if I it also allows for a   mismatch between the request name and the url by pasting the url as the name of the request, then changing the actual url of the request without updating the name.

I have two suggestions: 
1. Make it possible to leave the name blank, and if the name is blank, the url will show instead.
2. Don't even ask for the name upfront, thus defaulting to using the url as the name, while still allowing someone to explicitly name the request after creation.

The first is possible without the second, but I believe implementing both would significantly speed up the workflow.

**Comment by KarthikSiddarth** [comment]
can I tak this ?

**Comment by gschier** [comment]
Please do @KarthikSiddarthmif you are still willing 😊

**Comment by crisz** [comment]
The issue is closed, the PR is merged, but I still don't have the URLs as default names.
All my requests are named "new request", and I need to edit the name manually

**Comment by Jebarson** [comment]
@crisz can confirm even after over a year. Opened a new issue https://github.com/Kong/insomnia/issues/7970
