### ISSUE TITLE
PDF preview does not render text

### ISSUE THREAD

**Issue by betterphp** [Kong/insomnia#1533]
- Insomnia Version: 6.5.3
- Operating System: Ubuntu 18.10

## Details
When an endpoint returns a PDF the preview does not render any text.

This is from Insomnia
![image](https://user-images.githubusercontent.com/788007/58626493-db8e8300-82cc-11e9-96b7-38af27dda9c6.png)

This is the PDF saved using the _Save response body_ option.
![image](https://user-images.githubusercontent.com/788007/58626496-de897380-82cc-11e9-85ee-e82f011caf67.png)

This PDF was generated from PHP using FPDF and this code
```php
$pdf->SetDrawColor(0, 0, 112);
$pdf->SetFillColor(0, 0, 112);
$pdf->RoundedRect(5, 5, 200, 5, 2, "DF", "12");
$pdf->SetFont("arial", "b", 9);
$pdf->SetTextColor(255);
$pdf->Text(6.5, 8.5, "Such text, very missing, wow");
```
`RoundedRect` here is a function we added but the same thing happens when using `Rect`.

**Comment by gschier** [comment]
Can you attach the PDF file to this issue?

There isn't much we can do here either way. Insomnia uses pdfjs to render PDFs so, if this _is_ in fact an issue, it should be reported on that project instead.

**Comment by betterphp** [comment]
Sure here's the file. [example_file.pdf](https://github.com/getinsomnia/insomnia/files/3240365/example_file.pdf)

If I upload it to the [demo viewer page](https://mozilla.github.io/pdf.js/web/viewer.html) the text renders correctly.

Could it be something to do with the font not being available?

**Comment by jbonet** [comment]
This worked for me in previous version, today auto-updated and got not text pdf.

**Comment by veskoy** [comment]
PDF generated with iText also appears "blank" when displayed inside Insomnia. When opened via browser (both Chrome and Firefox) everything shows as expected.

**Comment by camflan** [comment]
I have this same issue, PDFs generated by Pentaho.

More information - when sending these PDFs via sendgrid API, the emails are also missing the text - but downloading via a browser on the same API _has_ text. 🤔

**Comment by gabuh** [comment]
Same issue here, PDFs are generated using Jasper (iText).

**Comment by betterphp** [comment]
Still an issue here.

**Comment by betterphp** [comment]
Not stale ya'll

**Comment by martisj** [comment]
![image](https://user-images.githubusercontent.com/661994/93190836-1f1c3300-f744-11ea-84b3-571ade8f0f7b.png)

I am getting this when loading a PDF.

**Comment by gedsonmarcelino** [comment]
> ![image](https://user-images.githubusercontent.com/661994/93190836-1f1c3300-f744-11ea-84b3-571ade8f0f7b.png)
> 
> I am getting this when loading a PDF.

I am with the same problem in version Insomnia Core 2020.4.0.

**Comment by gedsonmarcelino** [comment]
> > ![image](https://user-images.githubusercontent.com/661994/93190836-1f1c3300-f744-11ea-84b3-571ade8f0f7b.png)
> > I am getting this when loading a PDF.
> 
> I am with the same problem in version Insomnia Core 2020.4.0.

Guys, I updated to **version 2020.4.1** and it is working perfectly.

=)

**Comment by develohpanda** [comment]
We shipped #2645 in **2020.4.1** which resolves the last few comments, but I'm not sure if it resolves the initial bug report yet. Could somebody validate and report back, please?

**Comment by ranjan-purbey** [comment]
I tested the PDF on 2020.5.2 and the text renders correctly. We can close this issue perhaps.

**Comment by develohpanda** [comment]
Thanks @ranjan-purbey! 🙏🏽 Closed as resolved!
