### ISSUE TITLE
[Feature] Preview Content-Type application/jpeg as image

### ISSUE THREAD

**Issue by 4n70w4** [Kong/insomnia#1537]
![image](https://user-images.githubusercontent.com/38257723/58697043-7fe1f980-83a1-11e9-9579-4bbc0619318d.png)

![image](https://user-images.githubusercontent.com/38257723/58697051-87a19e00-83a1-11e9-9974-0d487acfba0e.png)

**Comment by filfreire** [comment]
Hi @4n70w4! thank you for reporting this issue and apologies for not getting an answer sooner!

The `image/jpeg` mime type is supported if you try to use our latest stable version. Example:

![Image](https://user-images.githubusercontent.com/11976836/180979628-4fb0a36c-fbe2-46e0-8746-069ffab79b71.png)

As for `application/jpeg` it seems it's an invalid mime type if we check the official RFC documentation:
- https://www.rfc-editor.org/rfc/rfc3745
- https://www.w3.org/Graphics/JPEG/
