### ISSUE TITLE
Basic authentication doesn't handle special French characters in password

### ISSUE THREAD

**Issue by jairbubbles** [Kong/insomnia#1558]
- Insomnia Version: 6.5.4
- Operating System: Windows 10

## Details

While investigating an authentication issue with Jira API (see https://bitbucket.org/farmas/atlassian.net-sdk/issues/460/cant-authenticate-when-password-contains), I tested the same requests with Insomnia.

Sadly Insomnia had the same issue and I couldn't authenticate as soon as my password contains a é.

It's probably related to the encoding too.

**Comment by jairbubbles** [comment]
While digging a little more I think what would make sense is to add a checkbox in insomnia to use ISO-8859-1 rather than UTF-8 (unchecked by default):

![image](https://user-images.githubusercontent.com/15875066/59439491-abc79b00-8df5-11e9-9033-83973b2a6a09.png)

More info on: https://stackoverflow.com/questions/7242316/what-encoding-should-i-use-for-http-basic-authentication

**Comment by gschier** [comment]
I'm open to accepting a PR for this if you'd like to submit one

**Comment by jairbubbles** [comment]
Humm... I might accept the challenge. I'll let you know!
