### ISSUE TITLE
[Improvement] HDR support 

### ISSUE THREAD

**Issue by fox-john** [Kong/insomnia#1574]
I have same bug for VS Code, look here : https://github.com/microsoft/vscode/issues/68069

In insomnia, screen is very black with HDR enabled.
Left = HDR screen, right = no HDR screen
![screen very black](https://i.imgur.com/H3LYVj1.jpg)

PS: Sorry for my bad english.

**Comment by gschier** [comment]
From the issue you liked, it looks like this may be a [workaround](https://github.com/microsoft/vscode/issues/68069#issuecomment-472994404) for now:

```
insomnia --force-color-profile srgb
```

**Comment by Dragoon1010** [comment]
@gschier thx ! It's work for now ! Great job :) !
