### ISSUE TITLE
[Feature Request] Merge JSON object variables from base & sub environment

### ISSUE THREAD

**Issue by 9errie** [Kong/insomnia#1580]
Variable in base environment:
```json
"app": {
  "clientId": "com.foo.someAppName"
}
```

Variable in sub environment XYZ:
```json
"app": {
  "clientSecret": "abc123"
}
```

Effective variable in environment XYZ:

Expected:
```json
"app": {
  "clientId": "com.foo.someAppName",
  "clientSecret": "abc123"
}
```

Actual:
```json
"app": {
  "clientSecret": "abc123"
}
```

Insomnia v6.5.4

**Comment by Gabrz** [comment]
If I could, I would like to upvote this Feature Request. 

I think it would add some more "user friendlyness" to the management of global/environment variables in Insomnia. You already provide way to store the variables in a structured JSON form, not merging the object variables kinda defeats that purpose.

When the item is a string, I understand that you override the base value with the environment value. But when the item is an object/array you should try to merge the 2 objects

![image](https://user-images.githubusercontent.com/37636455/61358845-7e01c600-a87b-11e9-9e68-31ce5e5ac70c.png)
and
![image](https://user-images.githubusercontent.com/37636455/61358878-9376f000-a87b-11e9-9ed2-75364109b545.png)

should lead to
![image](https://user-images.githubusercontent.com/37636455/61359567-d9808380-a87c-11e9-8f3f-8cb6c2fb414e.png)

**Comment by Gabrz** [comment]
Could you have a look at this @gschier? It says "Feature Request", but one could perhaps also argue that the current behavior is a bug?
Anyway, I have a pull request that implements this new Feature, and I think the (Environment) Variable management in Insomnia would really benefit from it.

**Comment by Gabrz** [comment]
Please don’t go stale!

**Comment by goldo** [comment]
I'd like/love this feature too ! It seems confusing without it, and I spent 10 mins wondering what was going on.

and mainly, thanks a lot for your great job @gschier

**Comment by Gabrz** [comment]
Good news everybody! The pull request was merged!

As of version 7.0.4 this feature is now available.

(This Issue/Request can be closed)

**Comment by goldo** [comment]
@Gabrz Great! Thx !

(Can't find the PR in the changelog tho:
https://insomnia.rest/changelog/7.0.4)

**Comment by Gabrz** [comment]
yeah, so sad, I'm not in the changelog. (my number of contributions did go up though)

But more important is, that the feature is in there, I've changed my environments and it works.

**Comment by goldo** [comment]
@Gabrz yep, tried it, it rocks ! Thanks again

**Comment by gschier** [comment]
Sorry @Gabrz I must have missed you somehow. I'll add you again in the next one
