### ISSUE TITLE
Invalid url when importing openAPI docs

### ISSUE THREAD

**Issue by mattaltepeter** [Kong/insomnia#1581]
We use a relative url to define our server endpoints as we have multiple environments and we don't want any cross-environment requests. When I try to import an OAS doc with this format, it fails due to invalid url.

```
servers:
  - url: /v1
```

![image](https://user-images.githubusercontent.com/3633108/60295148-04685f00-98f1-11e9-9007-fe3182e1b567.png)

Can the importer be updated for OAS to not reject these / is there any known work around?

**Comment by gschier** [comment]
I just took a look at this and it seems as though it is valid to have a relative URL here, as you do. Therefore, I'm okay with updating the code to accept this.

I have not yet worked on the OpenAPI import code so I'm not exactly sure which part of the system the logic this error is coming from. Are you interested in taking a look @maltepet? If not, can you post an example OpenAPI schema that can be used to reproduce this error?

Thanks!

**Comment by ranjan-purbey** [comment]
@mattaltepeter Can you please share an example schema to reproduce this issue?

**Comment by nijikokun** [comment]
Is this still an issue? @gschier

**Comment by gschier** [comment]
This was fixed by https://github.com/Kong/insomnia/commit/81ef50cc6b544099839c4b2cb68f95725630f17d#diff-3e6511e36aef998f36a821e63b58c1e7R63 and will be included in the next release.
