### ISSUE TITLE
[Feature Request] Remembering the format for the exported file

### ISSUE THREAD

**Issue by afuno** [Kong/insomnia#1592]
- Insomnia Version: 6.5.4 (6.5.4.2876)
- Operating System: macOS 10.14.5

## Details

I often export the workspaces. And I feel a little discomfort. Can you, please, to make memorizing the last selected format to export to this place?

For example, I prefer YAML. And I always have to do extra activities. No problem, when use this functionality rarely. But when often...

<img width="787" alt="Снимок экрана 2019-07-08 в 17 16 59" src="https://user-images.githubusercontent.com/2853419/60817788-01992400-a1a5-11e9-8b22-879dc0d067ea.png">

**Comment by afuno** [comment]
Also in this modal window (which is shown in the screenshot above) in some scenarios a cross (closing) disappears. Rarely, but still uncomfortable.

**Comment by tobiasr** [comment]
I would like to take a look at this, if ok?
