### ISSUE TITLE
[Feature Request] Enable / Disable Plugins

### ISSUE THREAD

**Issue by greggjs** [Kong/insomnia#1610]
- Insomnia Version: v6.5.4
- Operating System: OSX

## Details

While having plugins is great, I would like the ability to enable / disable them either at the global level, at the workspace level, or even at the request / folder level. I have times when I don't want a plugin to run, but there's no way to disable the plugin, which will block my request from going through and error from the plugin either not running a supporting side car application or the request I'm making does not pertain to the plugin so it fails the request based on the plugin's requirements to make the request. The current way to "disable" a plugin is to delete it from the plugins directory in the application, and then to "enable" it would just be to install it again. I feel that this experience is high friction, and adding simple enable / disable logic could make this experience smoother for consumers of the plugin.

#### Highest Priority
The ability to enable / disable plugins at the global level, from the plugin management view.

#### Low Priority (Stretch)
* The ability to enable / disable plugins from the workspace level
* The ability to enable / disable plugins from the request level

**Comment by greggjs** [comment]
Any thought into prioritizing this work? Would like your thoughts on this.

**Comment by gschier** [comment]
Ya I think this is an essential feature

**Comment by develohpanda** [comment]
@gschier @nijikokun yoink, I'd like to pick this one up 😄

![](https://media.giphy.com/media/3oEduXxyrVM2Lp76ow/giphy.gif)

Any thoughts on the stretch goals / if they are doable at this stage, or should I aim for enable/disable at a global level via the plugins tab in preferences?

**Comment by gschier** [comment]
Thanks @develohpanda, that'd be awesome! 😄 

I think a global level should be fine for now. What do you think about adding a `pluginConfig` map to the `Settings` model to contain an optional configuration property for each plugin?

```js
...
pluginConfig: {
  'default-headers': { disabled: true },
  'other-plugin': { disabled: true },
}
...
```

**Comment by greggjs** [comment]
Thank you so much for picking this up! 🎉 🎉

**Comment by develohpanda** [comment]
> What do you think about adding a `pluginConfig` map to the `Settings` model

Seems reasonable - I'll go down this path and use an indexer property for typing 😄
