### ISSUE TITLE
[Bug] Plugin dependencies' dependencies not installed correctly

### ISSUE THREAD

**Issue by LesterCovax** [Kong/insomnia#1613]
- Insomnia Version: 6.5.4
- Operating System: Windows 10 Pro, 1903

## Details

I installed `insomnia-plugin-regex` via the _Preferences/Plugins_ tab without issue, but ran into issues when installing the `insomnia-plugin-os` plugin.  It complains that it cannot fine the `esprima` module.  I tracked down the dependencies of `insomnia-plugin-os` ([LINK](https://github.com/getinsomnia/insomnia/blob/develop/plugins/insomnia-plugin-os/package.json#L17)), which is the NPM module `jsonpath`.  I then tracked down the dependencies of `jsonpath` ([LINK](https://www.npmjs.com/package/jsonpath?activeTab=dependencies)), which finally revealed the `esprima` dependency (along with 2 others).

Error output below:

> insomnia-plugin-os install error: Command failed: "C:\Users\user\AppData\Local\insomnia\app-6.5.4\Insomnia.exe" --no-deprecation C:\Users\user\AppData\Local\insomnia\app-6.5.4\resources\bin\yarn-standalone.js add insomnia-plugin-os --modules-folder C:\Users\user\AppData\Local\Temp\insomnia_6.5.4\insomnia-plugin-os-1564098003065 --cwd C:\Users\user\AppData\Local\Temp\insomnia_6.5.4\insomnia-plugin-os-1564098003065 --no-lockfile --production --no-progress
error C:\Users\user\AppData\Local\Temp\insomnia_6.5.4\insomnia-plugin-os-1564098003065\jsonpath: Command failed.
Exit code: 1
Command: node lib/aesprim.js > generated/aesprim-browser.js
Arguments: 
Directory: C:\Users\user\AppData\Local\Temp\insomnia_6.5.4\insomnia-plugin-os-1564098003065\jsonpath
Output:
internal/modules/cjs/loader.js:604
    throw err;
    ^
> **Error: Cannot find module 'esprima'**
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (C:\Users\user\AppData\Local\Temp\insomnia_6.5.4\insomnia-plugin-os-1564098003065\jsonpath\lib\aesprim.js:4:20)
    at Object.<anonymous> (C:\Users\user\AppData\Local\Temp\insomnia_6.5.4\insomnia-plugin-os-1564098003065\jsonpath\lib\aesprim.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)

**Comment by gschier** [comment]
Hmm, that's strange, I get the same error on macOS. I have a feeling it's maybe a limitation of using the bundled version of Yarn within Insomnia. You can get around this for now by manually running the install command within the plugins folder:

```shell
npm install insomnia-plugin-os
```

**Comment by halostatue** [comment]
When I run `npm install insomnia-plugin-os` in my `~/Library/Application Support/Insomnia/plugins` directory, nothing happens. Well, something happens, but nothing _useful_. To wit:

```
➜ npm install insomnia-plugin-os
npm WARN saveError ENOENT: no such file or directory, open '/Users/austin/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/austin/package.json'
npm WARN austin No description
npm WARN austin No repository field.
npm WARN austin No README data
npm WARN austin No license field.

+ insomnia-plugin-os@2.1.4
updated 1 package and audited 100 packages in 0.741s
found 0 vulnerabilities
```

It creates a `~/package-lock.json` and `~/node_modules`, but does not otherwise do anything to the `plugins/` directory.

**Comment by JohnRobson** [comment]
Same problem here.

`Failed to install insomnia-plugin-os

There may be an issue with the plugin itself, as a note you can discover and install plugins from the Plugin Hub.
Additionl Information
Error: insomnia-plugin-os install error: Command failed: /opt/Insomnia/insomnia.bin --no-deprecation /opt/Insomnia/resources/bin/yarn-standalone.js add insomnia-plugin-os --modules-folder /tmp/insomnia_2020.3.3/insomnia-plugin-os-1600654257796 --cwd /tmp/insomnia_2020.3.3/insomnia-plugin-os-1600654257796 --no-lockfile --production --no-progress
error /tmp/insomnia_2020.3.3/insomnia-plugin-os-1600654257796/jsonpath: Command failed.
Exit code: 1
Command: node lib/aesprim.js > generated/aesprim-browser.js
Arguments: 
Directory: /tmp/insomnia_2020.3.3/insomnia-plugin-os-1600654257796/jsonpath
Output:
internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (/tmp/insomnia_2020.3.3/insomnia-plugin-os-1600654257796/jsonpath/lib/aesprim.js:4:20)
    at Object.<anonymous> (/tmp/insomnia_2020.3.3/insomnia-plugin-os-1600654257796/jsonpath/lib/aesprim.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)

    at child_process__WEBPACK_IMPORTED_MODULE_3___default.a.execFile (file:///opt/Insomnia/resources/app.asar/bundle.js:94559:16)
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)`

**Comment by develohpanda** [comment]
> but does not otherwise do anything to the plugins/ directory.

If you run `npm install insomnia-plugin-os` within the `/plugins` directory, then go into the plugins list within Insomnia and hit "Reload Plugins", this should work. I was able to reproduce the installation error on macOS (it should be looked at and fixed), but I was also able to install it directly into the directory as a workaround for now.

**Comment by JohnRobson** [comment]
> > but does not otherwise do anything to the plugins/ directory.
> 
> If you run `npm install insomnia-plugin-os` within the `/plugins` directory, then go into the plugins list within Insomnia and hit "Reload Plugins", this should work. I was able to reproduce the installation error on macOS (it should be looked at and fixed), but I was also able to install it directly into the directory as a workaround for now.

Worked, Thank you so much.  $ ~/.config/Insomnia/plugins

**Comment by halostatue** [comment]
This should not be marked as `wontfix` by a bot. This is a real issue.

**Comment by develohpanda** [comment]
@halostatue which aspect is still an issue? The fact that you can't run `npm install insomnia-plugin-os` in the plugins folder, or that you can't install that plugin via Preferences > Plugins within the app?

Recent updates for Insomnia and this plugins seems to have resolved the original issue where the plugin could not be installed from the app itself.

With regards to `npm install insomnia-plugin-os`, it does not need to do anything to the `/plugins` directory itself. It creates a `package-lock.json` and `node_modules`, which itself contains the plugin, and Insomnia is able to consume that once you reload plugins.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/4312346/120269937-d40b7580-c2fc-11eb-8a46-3fa44c801a4d.png">

<img width="784" alt="image" src="https://user-images.githubusercontent.com/4312346/120270015-fac9ac00-c2fc-11eb-9e04-3a9ae6de5cd6.png">

Marking this issue as closed for now, but please comment if either of these do not work for you, and I will re-open it. 🙌🏽

**Comment by halostatue** [comment]
My objection was not that the issue was being marked for closure, but that a bot marked it `wontfix`. I stopped worrying about plugins for Insomnia a while back, so I haven‘t seen this in a while.

When I do get into dealing with some plugins again, I will test this and see if it’s still a problem so that it can be reopened.

**Comment by FischerRobson** [comment]
Hi, the same error is happened to me:
![image](https://user-images.githubusercontent.com/61335036/124041152-b2290f80-d9dc-11eb-931f-c00f553081bd.png)
Any plugin fails.
I already run `npm install insomnia-plugin-os` within the` /plugins` but the error remains
I tried to install the plugin by terminal, but failed to.

**Comment by turalasgarov** [comment]
For windows 10-11 users

`npm install insomnia-plugin-os`

Then the plugin you wan to install for example in my case `insomnia-plugin-xdebug`

`npm install insomnia-plugin-xdebug`

Go to C:\Users\YOUR_USERNAME\node_modules

cut 3 folders
![image](https://user-images.githubusercontent.com/108514118/177953872-4e06b9c7-f3ad-4117-9cf6-d5607d68c084.png)

Open Insomnia->Application->Preferences->Plugins

Press `Reveal Plugins Folder`

Paste copied items

Open Insomnia->Application->Preferences->Plugins

Press `Reload Plugins`

That's it!

Good luck!

**Comment by TuralAsgar** [comment]
For windows 10-11 users

`npm install insomnia-plugin-os`

Then the plugin you want to install for example in my case `insomnia-plugin-xdebug`

`npm install insomnia-plugin-xdebug`

Go to C:\Users\YOUR_USERNAME\node_modules

cut 3 folders
![image](https://user-images.githubusercontent.com/108514118/177953872-4e06b9c7-f3ad-4117-9cf6-d5607d68c084.png)

Open Insomnia->Application->Preferences->Plugins

Press `Reveal Plugins Folder`

Paste copied items

Open Insomnia->Application->Preferences->Plugins

Press `Reload Plugins`

That's it!

Good luck!
