### ISSUE TITLE
[Bug] Choose File sometimes crashes application

### ISSUE THREAD

**Issue by phillip-mofadeng** [Kong/insomnia#1621]
- Insomnia Version: v6.6.0
- Operating System: Ubuntu 18.10

## Details

This problem seems to have happened after the recent update. 

Everytime I click choose file, Insomnia would close/crash. Strange thing I noticed is clicking about  in Help does the same thing.

**Comment by rnstlange** [comment]
+ 1. Operating System: Ubuntu 18.04

**Comment by gschier** [comment]
Where are you clicking "choose file"?

**Comment by gschier** [comment]
I tried both Binary File Body as well as Multipart Form body and cannot seem to reproduce an error.

**Comment by phillip-mofadeng** [comment]
> Where are you clicking "choose file"? There are a few different places this could happen. A screenshot would be appreciated :)

![image](https://user-images.githubusercontent.com/53420490/62670655-178a4680-b9e8-11e9-8011-04a0bffff2f0.png)
As shown in screenshot, but the problem seems to be fixed after the automatic update to 6.6.2.

**Comment by gschier** [comment]
Hmm, that's strange. Nothing changed in v6.6.2 around file selection. I have a feeling there may be something strange going on so please report back if you see it again 😄

**Comment by vertho** [comment]
@gschier I have the exact same problem. running insomnia version 6.6.2 on Ubuntu 18.04.3
Following actions cause app to crash:
- Post request, body type multipart,  click on choose file
- Post request, body type binary file, click on choose file.
- Top menu bar, click help -> about. (all other menu items working fine)

**Comment by AllanDaemon** [comment]
Same problem here on Fedora 30, using the latest Snap version, 7.0.3.

It' doesn't always happen, but to me it's like 98% of the time.

I suspect it's something related with the GTK integration, right? Because it happens while I'm selecting the file, like browsing through the folders, before I could select the file to open. Usually, after the open file dialog opens, it crashes when I try to open or select any folder.

**Comment by AllanDaemon** [comment]
The terminal log. It crashed when I tried to change the folder location.

```
$ insomnia
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
[fix] Running database repairs
[db] Initialized DB at /home/user/snap/insomnia/37/.config/Insomnia/insomnia.$TYPE.db
Init responses DB
[localstorage] Initialized at /home/user/snap/insomnia/37/.config/Insomnia/localStorage
[main] Loading file:///snap/insomnia/37/resources/app.asar/renderer.html
[updater] Updater not running platform=linux dev=false
Gtk-Message: 14:46:04.522: GtkDialog mapped without a transient parent. This is discouraged.

(insomnia:13272): Gtk-WARNING **: 14:46:04.586: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/insomnia/37/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unable to load image-loading module: /snap/insomnia/30/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: libpng12.so.0: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
[1]    13272 abort (core dumped)  insomnia
```

**Comment by jaumarar** [comment]
Still happening. I cannot Import/Export a workspace

System: Ubuntu 19.04 and Ubuntu 16.10
Version: Insomnia 7.0.5 (lastest snap offered by Ubuntu Software app)

When importing/exporting a workspace the next error is thrown and the program closed
```
Could not load a pixbuf from icon theme. This may indicate that pixbuf loaders or the mime database could not be found.
Failed to load /snap/insomnia/47/data-dir/icons/Yaru/16x16/status/image-missing.png: 
Unable to load image-loading module: /snap/insomnia/37/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: cannot open shared object file: No such file or directory
```

Executing `ls /snap/insomnia/[37|47|current]/gnome-platform/` returns an empty folder. So i'm guessing that the folder is not properly mounted and therefore **gdk-pixbuf-2.0** cannot be found.

This can be replicated on a clean and updated Ubuntu 19.04 instalation so if you need any kind of info please ask for it.

**Comment by renatonolo** [comment]
I was trying with insomnia snap package and a was facing with this problem...
After uninstall snap package and install .deb package, this feature worked like a charm.

The bad news is that I didn't make a backup of my collection and I forgot that.. =X

Version 2020.2.2...

**Comment by Tahaan** [comment]
Exact same issue here, same errors. 

I was about to try the DEB package but fortunately saw renatonolo's comment above.

> I was trying with insomnia snap package and a was facing with this problem...
> After uninstall snap package and install .deb package, this feature worked like a charm.
> 
> The bad news is that I didn't make a backup of my collection and I forgot that.. =X
> 
> Version 2020.2.2...

**Comment by jameskennard** [comment]
Same problem for me, it happens everytime I try to browse for a file for a multipart body, and when I try to export my workspace.

```
(insomnia:14778): Gtk-WARNING **: 12:08:24.898: /snap/insomnia/77/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so: cannot open shared object file: No such file or directory

(insomnia:14778): Gtk-WARNING **: 12:08:24.898: Loading IM context type 'ibus' failed

(insomnia:14778): Gtk-WARNING **: 12:08:33.594: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/insomnia/102/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unable to load image-loading module: /snap/insomnia/77/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/insomnia/77/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
[1]    14778 abort (core dumped)  insomnia

$ ls /snap/insomnia/102/data-dir/icons 
total 0
$ ls /snap/insomnia/77/gnome-platform
total 0
```

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by samuelsogbesan** [comment]
Getting this same issue on M1 Macbook (2020) - has there been a resolution?
