### ISSUE TITLE
[BUG] Can't change keyboard binding for "Show Autocomplete"

### ISSUE THREAD

**Issue by spro** [Kong/insomnia#1633]
- Insomnia Version: 6.6.2
- Operating System: macOS Mojave 10.14.5

## Details

I use Alfred bound to ^-Space and it's too ingrained in my workflow to give up. I would like to change the the "Show Autocomplete" shortcut to something else, but no other shortcuts will trigger it. Interestingly it seems this key was the initial inspiration for customizable keybindings - #1162

### Steps to replicate

* Open keyboard preferences.
* Delete the existing "Show Autocomplete" shortcut.
* Deleted shortcut does not trigger autocomplete, as expected.
* Add Shift-^-Space, or Command-Shift-A, or anything else as the shortcut.
* **New shortcut does not trigger autocomplete.**
* Add ^-Space as the shortcut, or use reset to accomplish the same.
* Original shortcut triggers autocomplete, as expected.

**Comment by gschier** [comment]
Ah yes, thanks for bringing this up. It looks like that hotkey isn't hooked up to anything at the moment. The `ctrl-Space` value is still hardcoded into the Codemirror options.

**Comment by DanielPower** [comment]
I use Ctrl+Space for Alfred, so this makes autocomplete unusable for me in Insomnia.

**Comment by gevial** [comment]
I'm using Ctrl+Space for Spotlight, so can't use Show Autocomplete too.
Is there any way to paste vars without keyboard shortcut? Can't use Insomnia at all without that.

**Comment by brandonarbini** [comment]
I'm in the same situation. I'd love to see both keybindings option fixed and an alternate method of inserting variables/tags (maybe right click?).

**Comment by brandonarbini** [comment]
I figured out how to enter them manually...like so: `{% response 'body', 'req_78c3efdb0ffa49c79d23c77906e4b5ed', '$.data.transferToken.token', 'always' %}`. I hope this helps @gevial @DanielPower @spro @gschier.

**Comment by spro** [comment]
Ah thank you @brandonarbini from there I was able to figure out environment variables using double braces e.g. `{{ base_url }}` inside the address bar. At least makes Insomnia usable for me in the meantime!

**Comment by thewheat** [comment]
I've managed to take a crack at this and have managed to get keyboard shortcuts working but it requires reload of Insomnia at the moment https://github.com/Kong/insomnia/pull/2726

**Comment by spro** [comment]
Awesome, and the "you have to reload" text discussed in the pull request is certainly an improvement over the current experience of changing the shortcut and nothing happening.

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by crisz** [comment]
Was this solved? I'm still experiencing this bug in MacOS, since ctrl+space does nothing despite what docs say

**Comment by marcospb19-cw** [comment]
Update: still a bug, should be reopened.
