### ISSUE TITLE
Feature Request: Support Proof Key for Code Exchange (PKCE)

### ISSUE THREAD

**Issue by simardst** [Kong/insomnia#1653]
A lot of APIs are now supporting PKCE authentication flow for end-users (for mobile, native and SPA applications).

To explore and test those APIs, obtaining a token with this flow is complex to do manually. 

It would be a great addition to Insomnia if a user/tester could authenticate itself using PKCE flow.

**Comment by petejohansonxo** [comment]
Is this really stale? Seems a valid feature request I'd love to see in Insomnia.

**Comment by BeeHiveJava** [comment]
We would also love to see this, we use this a lot in production in our company.

**Comment by fmeriaux** [comment]
We use it too, it'd be really cool to have it.

**Comment by 0xdevalias** [comment]
If this doesn't land here anytime soon, postman should have it added soon it seems: https://github.com/postmanlabs/postman-app-support/issues/3825

There was also a workaround posted by @clementcur in https://github.com/postmanlabs/postman-app-support/issues/3825#issuecomment-580786136

**Comment by brechtvhb** [comment]
Any update / ETA on this feature?
