### ISSUE TITLE
[Question] Parsing output of headers

### ISSUE THREAD

**Issue by paul** [Kong/insomnia#1656]
- Insomnia Version: 6.6.2
- Operating System: Fedora 30

## Details

Bullhorn's API has a really odd authentication scheme that involves making a request with the username and password which then 302 redirects with a `Location` header to a URL that contains a query param of `code`. This code is then used to make another request to get `access_token` and `secret_token`. I'm trying to automate this using insomnia, but I'm not sure its possible with the templating currently.

The header I get back looks like this:

```
https://myapp.example/auth/bullhorn/callback?code=91%3Aa9168bbd-{snip}&client_id={snip}
```

I have to extract that `code=` param, so I cobbled together some really gross nunjucks template stuff:

```json
{
  "location": "{% response 'header', 'req_9d0b9d304c1f435b9071199fcfb0547d', 'b64::TG9jYXRpb24=::46b', 'never' %}",
  "code": "{{ location | replace('https://myapp.example/auth/bullhorn/callback?code=', '') | replace('%3A', ':') | truncate(39, true, '') }}",
}
```

In the environment "Edit variable" modal, this seems to work OK, I get the extracted string in the preview textarea:

![image](https://user-images.githubusercontent.com/184/63815482-f1bed600-c8f1-11e9-9c53-61aad87a7e72.png)

But, when I try to use that environment variable in a query param in another request, I get a request render error `TypeError: Cannot read property 'type' of null`

![image](https://user-images.githubusercontent.com/184/63815525-29c61900-c8f2-11e9-84fe-dc66974a2612.png)

Is there a better way to accomplish this? Or am I just abusing these templates too much? 

Thanks!

**Comment by paul** [comment]
Its kinda like to OAuth2, maybe the developers heard somebody describe it in a bar, and decided to implement it without any further investigation. I tried the OAuth2 helper, but it doesn't seem to handle this particular weird implementation.

Here's the flow we have to use:

1. Make a GET request to `/oauth/authorize` with username, password and client_id params
2. Response is a 302 redirect to our app with some query params, one of which is `code`.
3. Make a POST request to `/oauth/token` with code, client_id, client_secret
4. Response is JSON with an access_token with 10m expiry and a refresh token
5. Make a GET request to `/rest-services/login` with access_token
6. Response is JSON with a `BhRestToken`, which also expires.
7. Use BhRestToken for all other API calls.

The wrinkle is that when the `access_token` expires, they provide a `refresh_token` grant_type at `/oauth/token`, but this returns a new refresh token, and invalidates all other refresh tokens. This means that our web application that consumes this API is generating a new `refresh_token` every 10 minutes, so we can't share/re-use it between other applications or have developers use it. Instead, we store the username/password, and just restart the whole auth flow from the beginning every time.

I've been having to make the login request in Insomnia, look at the "Timeline" tab, carefully copy/paste the `code` query param, replace the `%3A` with `:`, and update the `code` param in the "get access token" request. And I have to do this every 10 minutes, or sooner if another dev is doing the same thing. Being able to script this in insomnia would be a huge time-saver.

Here's my environment:
![image](https://user-images.githubusercontent.com/184/63958621-eda4cc80-ca47-11e9-9e87-2a113db5d539.png)

And the request where I'm trying to access `code` from the environment:
![image](https://user-images.githubusercontent.com/184/63958783-0f9e4f00-ca48-11e9-9413-8d95ef429693.png)

It seems like it might be related to the `truncate` filter. But it also seems the `replace` filter isn't doing anything either? Here's some tests I've tried:

I'm using a `location` environment with value: `https://app.textus.com/auth/bullhorn/callback?code=91%3A5ee2d9c9-016f-41d0-8752-a7693bd5b8f7&client_id=d7cc0291-[snip]`
I have a Request set up to use `{{ code }}` as a parameter, where I'm varying the `code` environment, and here's the results I get:

| code | result | |
| --- | --- | --- |
| `{{ location \| replace('https', '') }}` | `&code=https%3A%2F%2Fapp.textus.com...` | Not replacing the "https" |
| `{{ location \| replace('https', '') \| replace('app.textus.com', '') }}`  | `&code=https%3A%2F%2Fapp.textus.com...` | Not replacing anything |
| `{{ location \| truncate(40) }}` | Render error: "expected name as lookup value, got ." | |
| `{{ location \| truncate(40, true, '') }}` | Render error: TypeError: "Cannot read property 'type' of null" | |

Seems like the `replace` filter just doesn't do anything (or maybe I'm using it wrong), and the `truncate` filter just breaks. I've noticed the template builder ui creates templates like `{% %}`, which doesn't work with the filters. I'm using `{{ }}` in this case, which works fine in the template builder ui preview, but doesn't seem to work when making requests.

**Comment by paul** [comment]
I don't think this is stale, I've been waiting for an answer, if this is a problem in how I'm trying to use the scripting features of insomnia, or if the scripting itself has a bug. I can try and provide more information, if needed.

**Comment by gschier** [comment]
Correct, you can't use template tags within filters. However, You _can_ store the URL into a `location` variable and operate on the new variable like you are doing.

Using Insomnia's plugin system, you could create a new Regex template tag to more easily pull the value out of the variable. https://support.insomnia.rest/article/26-plugins#template-tags

**Comment by gschier** [comment]
Hmm, actually, I think your errors might be the same problem as https://github.com/Kong/insomnia/issues/1809

One thing you could do is fork the Response Tag built-in plugin and extend it to extract the code you want. https://github.com/Kong/insomnia/blob/develop/plugins/insomnia-plugin-response/index.js

**Comment by filfreire** [comment]
Closing as stale
