### ISSUE TITLE
Hangs when loading a file owned by root

### ISSUE THREAD

**Issue by Schparky** [Kong/insomnia#1665]
- Insomnia Version: 6.6.2 (snap)
- Operating System: Ubuntu 18.04.3 LTS

## Details
1. Set up a Multipart request where at least one part is a File
2. Select a file outside the snap filesystem (e.g. ~/foo.txt)
3. Click "Send"

Expect: request is sent

Actual behavior: Indefinite wait with timer counting and spinner turning. "Cancel Request" stops the wait timer.

**Comment by Schparky** [comment]
After further investigation (sorry, should have checked this before posting) the issue is not be a result of the file location, but file permissions. I assumed that since other processes could read the file, that it was only due to the location of the file. The file that caused the issue was owned by root, with 644 permissions.

**Comment by UkiahSmith** [comment]
I'm glad you were able to resolve this with changing the file permissions.

**Comment by Schparky** [comment]
@UkiahSmith while I was able to resolve the problem, I chose not to close the issue because the way the UI handled the file permission issue was not correct. The file was readable, so it should have been able to open the file. Besides, the lack of a proper error message didn't help me diagnose what was happening.
