### ISSUE TITLE
[Question] Is there a way to call and result from a different plugin?

### ISSUE THREAD

**Issue by starx** [Kong/insomnia#1687]
- Insomnia Version: 6.6.2
- Operating System: Ubuntu

## Details

I am trying to compose a plugin for moment.js support and I was wondering If there was a way I could call functions & implementation of a different plugin and get some data back which I can use in my implementation of moment.js.

**Comment by gschier** [comment]
There is no standard way to do this, no. Can you provide an example of what you are trying to do? Perhaps there is another way of achieving it.

**Comment by starx** [comment]
@gschier I wanted to get the values from `insomnia-plugin-faker` plugin and pass the output to another plugin to process the value e.g. formatting the data.

**Comment by filfreire** [comment]
Hello @starx thanks for reporting this!

We have noticed that you at one point created the plugin (example [starx/Insomnia-Plugin-Faked-Moment](https://github.com/starx/Insomnia-Plugin-Faked-Moment/blob/master/index.js)).

Feel free to reopen this issue, or open a new one if you are still having problems.
