### ISSUE TITLE
Fetch API stringify

### ISSUE THREAD

**Issue by zbot473** [Kong/insomnia#1691]
- Insomnia Version: 6.6.2
- Operating System: macOS

## Details

[Bug]

The generated fetch snippet is outputted as an object. The fetch API only accepts stringified values, at least with the "application/json" content type. This switch results in HTTP endpoints being passed [Object object], instead of the actual body.

**Comment by jawahars16** [comment]
Can you elaborate a little bit? Because I am able to generate a proper fetch code with actual JSON body.

![image](https://user-images.githubusercontent.com/14835387/66254753-7413a300-e798-11e9-9791-8f3435219db7.png)

![image](https://user-images.githubusercontent.com/14835387/66254759-94436200-e798-11e9-9845-91f6d0412165.png)

**Comment by gschier** [comment]
I think what they are saying is that you are not allowed to set `body:` to a JS object. It will try to cast it to a string and send `[Object object]` instead.

These are the only acceptable types for the `body:` attribute:

![image](https://user-images.githubusercontent.com/587576/66355048-9f72cb00-e91b-11e9-86f2-15e615511614.png)

via https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by gschier** [comment]
Insomnia uses `httpsnippet` to generate code snippets and it looks like there is already an open PR to fix this https://github.com/Kong/httpsnippet/pull/145

**Comment by zbot473** [comment]
> I think what they are saying is that you are not allowed to set `body:` to a JS object. It will try to cast it to a string and send `[Object object]` instead.
> 
> These are the only acceptable types for the `body:` attribute:
> 
> ![image](https://user-images.githubusercontent.com/587576/66355048-9f72cb00-e91b-11e9-86f2-15e615511614.png)
> 
> via https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

Exactly what I meant

**Comment by zbot473** [comment]
Their PR is erroring out though. I'm not sure why.

**Comment by develohpanda** [comment]
Has been fixed by https://github.com/Kong/httpsnippet/pull/179 - cc: @jgiovaresco
