### ISSUE TITLE
plus sign escaped improperly

### ISSUE THREAD

**Issue by jvlasblom** [Kong/insomnia#1712]
- Insomnia Version: 6.5.3.2835
- Operating System: OS X 10.14.6

## Details

When pasting a URL containing a + sign (either the URL or the curl command), the plus sign is escaped improperly:

Example:
This URL returns search result hits in all browsers, and with curl:

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=science%5bjournal%5d+AND+breast+cancer+AND+2008%5bpdat%5d&retmode=json

It returns no results in insomnia.   The Insomnia 'timeline' shows the request is being mangled to:
GET /entrez/eutils/esearch.fcgi?db=pubmed&term=science%5Bjournal%5D%2BAND%2Bbreast%2Bcancer%2BAND%2B2008%5Bpdat%5D&retmode=json HTTP/1.1

As noted, curling the URL returns correct results:
curl 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?retmode=json&db=pubmed&term=science%5bjournal%5d+AND+breast+cancer+AND+2008%5bpdat%5d'

**Comment by orthur** [comment]
- Insomnia Version: 7.0.0.3015
- Operating System: OS X 10.14.6

I have the same issue with comma character `,` converts to `%2C`
If it is expected behaviour then is it possible to turn conversion off?

**Comment by ranjan-purbey** [comment]
Yes, the behaviour is the same on 7.0.2. Both "+" and "," belong to the reserved characters set of URI specification and should not be escaped, I think. For those who want to enable escaping, we can add a checkbox

**Comment by ranjan-purbey** [comment]
As you can read in the RFC, whether or not reserved characters are encoded should depend on the application. If they're being used as delimiters, they shouldn't be escaped imho

**Comment by Botono** [comment]
Escaped characters should not be decoded before making a request. How else would you sent a single comma-delimited value in a URL?

Example:

`https://my.test.server.com/v1/foo?var=foo%2Cbar%2Cbaz`

This should be sending a query string variable called `var` with a value of `"foo,bar,baz"`. However, Insomnia converts it before sending the request, like so:

`Preparing request to https://my.test.server.com/v1/foo?var=foo,bar,baz`

<img width="710" alt="Screen Shot 2020-05-26 at 11 37 54 AM" src="https://user-images.githubusercontent.com/1622358/82937645-60929380-9f45-11ea-80e2-950666cad77e.png">


I have reproduced this just now in Mac OS version 7.1.1.3350.  In fact his bug is preventing me from using Insomnia to test recent changes to my API.

**Comment by superhawk610** [comment]
For what it's worth, this is different from what Postman, Chrome, and `curl` do (to name a few), and can cause problems that are very difficult to debug. As explained in RFC 3986

> Percent-encoding a reserved character, or decoding a percent-encoded octet
that corresponds to a reserved character, will change how the URI is
interpreted by most applications.

This means that replacing a `+` with `%2B`, for example, meaningfully changes the URL. If Insomnia chooses to make that replacement (which it currently does), it should at least be reflected in the URL bar to make that replacement clear to the user.

IMO, this behaviour should be changed (or at least moved behind a flag, as @ranjan-purbey suggested), to bring it in line with other common network tools and make it so that the URL shown in the bar matches what's received by the server.

**Comment by wongstein** [comment]
My very quick test of the endpoint provided on the latest Insomnia (2022.5.1) did not reproduce this error.

![Image](https://user-images.githubusercontent.com/12381507/185960040-b9a3799b-f4f8-43f0-bbe8-2f2613798e40.png)

I'm cognizant to @superhawk610 explanation of the behavior which we'll keep in mind next time we are touching the implementation of special characters and the request library.  I'm going to close this issue for now, feel free to open another one (or re-open this one) if you find that you can reproduce it with the latest version of Insomnia
