### ISSUE TITLE
Broken icon on Linux

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [Kong/insomnia#1717]
- Insomnia Version: 7.0.1
- Operating System: Arch Linux 5.3.5

## Details

I think 7.0.1 broke the desktop icon again:

![image](https://user-images.githubusercontent.com/12160864/66507815-44b9aa80-eaa6-11e9-8af0-edcaf6eabda5.png)

I'm using Gnome 3.34.1

**Comment by matthewarmand** [comment]
Also on Arch, installed Insomnia 7.0.1 via AUR and also seeing this issue with KDE Plasma 5.16.5

**Comment by thejoaov** [comment]
Also in Ubuntu 19.04, installed via .deb package.

**Comment by krasoffski** [comment]
I have the same problem on Xubuntu 18.04 on Insomnia version 6/7.
Installed via deb package.
Similar Electron apps have correct icon in task bar.

![image](https://user-images.githubusercontent.com/1073415/66558960-3084b480-eb5d-11e9-8fb2-d8c4528fede4.png)

**Comment by rhaces** [comment]
Same issue, Ubuntu 19.04 installed via repository

**Comment by christianlmc** [comment]
**Found a (temporary) solution on Ubuntu 18.04:**

On your terminal, run:
`locate insomnia.png`

It should show something like this:
```bash
/usr/share/icons/hicolor/0x0/apps/insomnia.png
```

Now edit the insomnia.desktop file (**BACKUP THIS FILE BEFORE EDITING**):
```bash
sudo nano /usr/share/applications/insomnia.desktop
```

Change the 'Icon' line to reflect the following:
```bash
Icon=/usr/share/icons/hicolor/0x0/apps/insomnia.png
```

Close any opened instances of Insomnia and open a new one, the icon should show now

**Comment by matthewarmand** [comment]
Fix worked for me on Arch as well, and the icon showed up in the same location.

It'd still be good to get a fix to the installation process so this doesn't happen

**Comment by gschier** [comment]
Hmm, strange. Probably an easy fix but is frustrating that this keeps happening. Will fire up a VM and get this one fixed for the next release.

**Comment by michelgds** [comment]
It happens on Ubuntu 16.04.6 LTS (Xenial Xerus). That fix works for me. Thank you @christianlmc!

**Comment by krasoffski** [comment]
Did not for Xubuntu 18.04. (((

**Comment by julio899** [comment]
> excellent I can resolve  copy the file **insomnia.png**  in this folder **/usr/share/icons/hicolor/0x0/apps/** 
and mod the file **/usr/share/applications/insomnia.desktop** 
 in Line **Icon=/usr/share/icons/hicolor/0x0/apps/insomnia.png**

**Comment by sharifzadesina** [comment]
Same on 7.0.3

**Comment by gschier** [comment]
Just got an Ubuntu VM going so I can work on a fix

**Comment by gschier** [comment]
The AppImage seems to be fine, which is weird

**Comment by wdolorito** [comment]
I fixed this in elementary OS by linking the icon in to /usr/share/pixmaps:

`sudo ln -s /usr/share/icons/hicolor/0x0/apps/insomnia.png /usr/share/pixmaps`

Log out, then log back in and the icon should appear.

**Comment by coyoterj** [comment]
That fix works for me. Thank you @wdolorito !

- Insomnia: 7.03
- OS: Pop!_OS 19.10
- Gnome: 3.34.1

**Comment by krasoffski** [comment]
Does not work for Xubuntu 18.04

**Comment by wdolorito** [comment]
> Does not work for Xubuntu 18.04

I was curious about this, since elementary is built on ubuntu 18.04 as well, so I downloaded an ISO and installed Xubuntu in a VM.  After installing insomnia from the repos, as expected, the icon did not appear in the menus.  I linked the icon as I did in eOS, logged out, logged back in and the icon showed up.  Are you still experiencing the problem?

**Comment by christianodejesus** [comment]
Same here on Insomnia 7.0.3 running on Linux Mint 19.1 and 19.2.

**Comment by sidneisimeao** [comment]
@christianodejesus ,
I was able to display the icon on the desktop by changing the Icon entry:
Icon=/usr/share/icons/hicolor/0x0/apps/insomnia.png

**Comment by yuridamata** [comment]
> Same here on Insomnia 7.0.3 running on Linux Mint 19.1 and 19.2.

The workaround worked for me.

**Comment by gschier** [comment]
Can you all give this new Beta build a try and let me know if it works? Seems to be working on my Ubuntu install for AppImage, Snap, and deb

https://github.com/getinsomnia/insomnia/releases/tag/v7.0.4-beta.6

**Comment by GekovIN** [comment]
> Can you all give this new Beta build a try and let me know if it works? Seems to be working on my Ubuntu install for AppImage, Snap, and deb
> 
> https://github.com/getinsomnia/insomnia/releases/tag/v7.0.4-beta.6

Works on Ubuntu 16.04 LTS, thanks

**Comment by gschier** [comment]
Awesome, thanks for letting me know!

**Comment by krasoffski** [comment]
![image](https://user-images.githubusercontent.com/1073415/69874208-79d6c200-12cb-11ea-9ee9-c8927b923381.png)

Xubuntu 18.04 problem still present.

**Comment by rafaelrenanpacheco** [comment]
Is this still an issue?

**Comment by rst5nn** [comment]
Not sure this is the latest version but issue still exists.
![image](https://user-images.githubusercontent.com/1073415/78231591-b7e32d00-74db-11ea-8393-7c9c40c49f53.png)

**Comment by tcelestino** [comment]
Insomnia Designer v2020.1.3 on Ubuntu 18.04

![Screenshot from 2020-05-04 17-25-28](https://user-images.githubusercontent.com/190265/81010463-bbe0d280-8e2c-11ea-8555-0b592f83d3a5.jpg)

**Comment by dimitropoulos** [comment]
This appears to no longer be happening in XFCE or KDE

![Screenshot_20210702_161351](https://user-images.githubusercontent.com/15232461/124324157-8333aa80-db50-11eb-938f-3b765f6a4678.png)

![Screenshot_20210702_161535](https://user-images.githubusercontent.com/15232461/124324314-bece7480-db50-11eb-8435-dfe1f861f467.png)
