### ISSUE TITLE
[Bug] Snap v7.0.1 does not start anymore

### ISSUE THREAD

**Issue by bmarwell** [Kong/insomnia#1720]
- Insomnia Version: Snap v7.0.1 2019-10-08 stable
- Operating System: Ubuntu 18.04.3 LTS

## Details

The snap was refreshed to 7.0.1 recently. Since then, it does not start. No stderr or stdout output is given That's all.

### Expected behaviour

Insomnia starts or outputs an error.

### Actual behaviour

No life sign. Even the shell command does not show any error messages.

## Workaround

None for this version yet. But  `sudo snap revert insomnia` will revert to 6.5.4, which will start just fine.

## Further diagnosis

`journalctl` shows:
```
Okt 10 09:37:10 hostname audit[11156]: AVC apparmor="DENIED" operation="capable" profile="/snap/core/7713/usr/lib/snapd/snap-confine" pid=11156 comm="snap-confine" capability=4  capname="fsetid"                                       
Okt 10 09:37:10 hostname kernel: audit: type=1400 audit(1570693030.744:429): apparmor="DENIED" operation="capable" profile="/snap/core/7713/usr/lib/snapd/snap-confine" pid=11156 comm="snap-confine" capability=4  capname="fsetid"     
```
I'd expect this is harmless.

`strace insomnia` yields:
```
write(2, "need to run as root or suid", 27need to run as root or suid) = 27
write(2, "\n", 1
```
Huh?

**Comment by wongstein** [comment]
It's been awhile since this bug was reported, but I wanted to check in to see if it was still reproducible with the latest versions of everything.

**Comment by bmarwell** [comment]
I cannot reproduce this issue anymore, as I am not using ubuntu anymore. I switched to Manjaro + AUR. Thanks anyway.
