### ISSUE TITLE
Unable to use environment variables in graphQL query editor

### ISSUE THREAD

**Issue by douglas-gibbons** [Kong/insomnia#1731]
- Insomnia Version: 7.0.1.3041
- Operating System: MacOs 10.15 Catalina

## Details

Steps to reproduce:

1. Launch insomnia 
1. Create and select a new workspace
1. Select manage environments and set base environment to be:
```
{
  "foo": "bar"
}
```
4. Create a new request
1. In the request, select type as GraphQL Query
1. In the GraphQL tab press [command][space]

### Expected results
Variable drop-down should appear allowing user to select variables

### Actual results
No drop-down appears. User unable to select variables. Typing "foo" also does not bring up the variable selection.

Variable selection _does_ work in other tabs, such as entering Header information, or the URL field.

Ref: #1169 - The resolution here did not work.

**Comment by gschier** [comment]
Can you explain why #1169 didn't work for you? 

Template variables are not supported inside the GraphQL query editor

**Comment by wongstein** [comment]
Closing this issue due to lack of interaction.
