### ISSUE TITLE
[Bug] Re-login dialog spammed when logged out due to session expiration

### ISSUE THREAD

**Issue by Arteneko** [Kong/insomnia#1732]
- Insomnia Version: 7.0.1
- Operating System: Can reproduce on MacOS 10.14, Windows 10 pro and ArchLinux

## Details

When, for some reason, the user's logged out due to the session expiring, he's constantly interrupted with a new dialog asking him to re-login.

<img width="874" alt="Screenshot 2019-10-17 at 13 47 44" src="https://user-images.githubusercontent.com/23583792/67006298-14e15700-f0e5-11e9-9b0b-031cf4dea25f.png">

When the user is explicitly dismissing the dialog, by pressing the Esc key, clicking the top-right dismiss button, or clicking outside of the dialog window, it should be remembered, and disable Plus features until re-login; not spam the user with login requests.

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by wongstein** [comment]
Hi @Arteneko !  There's been a lot of changes in Insomnia since this issue was first posted.  Are you still able to reproduce this with the latest version (2022.4.2)?

**Comment by Arteneko** [comment]
Nope, not anymore. However, in the meantime I reinstalled my computer a few times so maybe it was due to cache/config issues I cannot test anymore

**Comment by wongstein** [comment]
Great!  Thanks for checking in again!
