### ISSUE TITLE
[Feature Request] Pin/Bookmark Responses and XPATH/JSON Path with name or metadata

### ISSUE THREAD

**Issue by susamn** [Kong/insomnia#1733]
- Insomnia Version: Version 7.0.0 (7.0.0.3015)
- Operating System: macOS Catalina (10.15)

## Details

It would be really helpful to have a feature to pin or bookmark 

- Response
- XPath
- JSON Path

Now as we continue to use insomnia all the responses get stacked as they are executed and old responses are lost, this is also same for XPath or JSON path, as there is no preview for both of them, I keep on trying till I get the correct one and all of the tries are saved, which are not needed at all. As these trials are saved old important ones are lost.

It would be awesome to have them pinned with a name like:

<Sample XPATH Query> - Gives the device details from a response etc.

The same for a response with some metadata like why it is important and the timestamp is already there.

**Comment by kreosus** [comment]
Hi @susamn,

Thank you for reporting this issue and suggestion. It is not in our roadmap for a future release yet. Once again, thank you for the suggestion and have a nice day.
