### ISSUE TITLE
[Question] JSONPath Sort Array

### ISSUE THREAD

**Issue by sergeiwaigant** [Kong/insomnia#1734]
- Insomnia Version: 7.0.0
- Operating System: Win10

## Details

Hi folks,

I try to use the Insomnia JSONPath implementation to play with the JSON output I get from the REST call.
Can someone tell me how to do the following things on the JSON example below?

- Sort the array
- Select second element
- Select elements starting with ....

```
[
  "myResponse1",
  "myResponse4",
  "myResponse3",
  "myResponse3"
]
```

The only filter that worked for me was `$.*` but this is nonsense ... -.-

Thanks!
Regards
-Sergei

**Comment by Tarig0** [comment]
* sort - not part of the default jsonpath
* second element - $.[1] should do it
* Select elements starting with .... - unfortunately $.[?(@=~ /myR.*/i)] is valid on http://jsonpath.herokuapp.com/ but this doesn't seem to be part of the package insomnia uses

**Comment by gschier** [comment]
You can type JS into the filter so `$..[?(@.match(/^foo/))]` should work (untested)

**Comment by sergeiwaigant** [comment]
Thanks @gschier its working!
Any idea how to extend this with sorting function? I am not that familiar with JavaScript... :/

**Comment by gschier** [comment]
I don't think the library we use supports sorting unfortunately https://github.com/dchester/jsonpath/blob/master/README.md

**Comment by codedemonuk** [comment]
You can use the following jsonpath query to select elements in the array starting with `my`

```
$[?(@.match(/my.+/i))]
```
