### ISSUE TITLE
[BUG] url autocomplete window doesn't go away until application restart

### ISSUE THREAD

**Issue by dpanda** [Kong/insomnia#1738]
- Insomnia Version: 7.0.1.3041
- Operating System:  macOs 10.14.5 

## Details

Sometimes, when typing an url the autocomplete window shows up and does not go away (only solution is to close and reopen the application).

If you click on one item, the url stays the same, but in the "Url preview" under the "Query" tab you can see that the item was actually prepended to the url.

**Comment by filfreire** [comment]
Closing as stale. We have a similar bug on latest version https://github.com/Kong/insomnia/issues/5214
