### ISSUE TITLE
Allow setting macOS dark mode manually

### ISSUE THREAD

**Issue by muuvmuuv** [Kong/insomnia#1741]
On macOS, Insomnia dark themes look way better with the window having macOS
 dark mode set. I don't know if it is possible but some Apps like Slack have an option to prefer one theme fixed or dynamically by the OS. Would be cool for Insomnia too.

![Bildschirmfoto 2019-10-18 um 22 59 07](https://user-images.githubusercontent.com/11534760/67128047-e655a000-f1fa-11e9-85b5-4fee25e6ca38.png)

**Comment by gschier** [comment]
I agree it would be awesome to support this. It doesn't look like there is an easy way with Electron though. Have you found anything?

**Comment by muuvmuuv** [comment]
The only think I have found is this https://github.com/electron/electron-packager/blob/master/docs/api.md#darwindarkmodesupport @gschier but I think this is just for packaging and would completaly force it. Wonder how Slack did it. What does the Electron API says?

Ah okay. Settings this `nativeTheme.themeSource` to `dark` should do it: https://electronjs.org/docs/api/native-theme#nativethemethemesource

**Comment by muuvmuuv** [comment]
Requires Electron `7.x`... maybe Insomnia should get some updates before considering implementing this ^^

**Comment by gschier** [comment]
Yes, there is a roadmap task to update Electron as we are quite behind at the moment

**Comment by condemil** [comment]
It will be great if there will be a way to separately select dark and light theme, like some other Electron apps. This way when macOS automatically switches between light/dark mode it will also be handled automatically by Insomnia. Here is an example how it can be done: https://www.electronjs.org/docs/tutorial/dark-mode#example

**Comment by dimitropoulos** [comment]
I believe that https://github.com/Kong/insomnia/pull/2868 addresses this issue.  If I am mistaken please let me know and we can reopen this isssue.

I'm not entirely sure, but if, by chance, we're talking about https://github.com/Kong/insomnia/issues/3177 then let's move forward with considering that issue the main one (and this, therefore a duplicate).
