### ISSUE TITLE
[Feature Request] Allow bulk edit for form

### ISSUE THREAD

**Issue by tdchien** [Kong/insomnia#1745]
I tried to input many param with body type Form URL Encoded or Form multi-part and noticed it would be better if we can have bulk edit like `Header` and a exist request feature for query param #1110 
Hope this function will be accept and add to insomnia in the next release.
Thank for your efforts

Insomnia 7.0.3

**Comment by salvadorjhai** [comment]
> I tried to input many param with body type Form URL Encoded or Form multi-part and noticed it would be better if we can have bulk edit like `Header` and a exist request feature for query param #1110
> Hope this function will be accept and add to insomnia in the next release.
> Thank for your efforts
> 
> Insomnia 7.0.3

still not available on 7.1.1

Its hard to input 111 lines of form data, so yes, hope bulk edit will be added on the next update.

**Comment by salvadorjhai** [comment]
> I tried to input many param with body type Form URL Encoded or Form multi-part and noticed it would be better if we can have bulk edit like `Header` and a exist request feature for query param #1110
> Hope this function will be accept and add to insomnia in the next release.
> Thank for your efforts
> 
> Insomnia 7.0.3

you can select 'Other', paste your url encoded post data then select 'Multi part' -> just click OK when ask that your post data will be lost.

insomnia 7.1.1
