### ISSUE TITLE
[Feature Request] Better handling of expired OAuth 2 refresh tokens

### ISSUE THREAD

**Issue by timewasted** [Kong/insomnia#1749]
- Insomnia Version: 7.0.3
- Operating System: Windows 10 (feature request is not OS dependent, however)

## Details

I'm working with an API that uses OAuth 2 for authorization, and things mostly work as expected.  The issue is that Insomnia doesn't handle expired refresh tokens, which leads to a workflow of:

1. Send request which fails with an HTTP `400 Bad Request` status code and a body of
```
{
  "error": "invalid_grant",
  "error_description": "Refresh token expired"
}
```
2. Click to `OAuth 2` tab for request.
3. Click `Refresh Token` button.  See same failure as above.
4. Click `Fetch Tokens` button.
5. Resend request which is now successful.

This is obviously not an ideal workflow.  Looking at `packages/insomnia-app/app/network/o-auth-2/refresh-token.js` I see that it's just checking for a 401 response and handling that properly, but throwing an error on every other status.  My proposal for how to fix this would be something like:

```
if (statusCode === 400) {
  const bodyBuffer = models.response.getBodyBuffer(response);
  // Check existence of "error" and "error_description" fields in response.
  // If "error" field is "invalid_grant" and "error_description" field
  // is "Refresh token expired", treat response same as a 401 status.
}
```

This should make the workflow become:

1. Send the request which fails with an HTTP `400 Bad Request` status with the above body.  Code sees that it failed due to an expired refresh token and re-authorizes in the background, causing it to re-send the request with valid tokens which allows the request to succeed.

Now the obvious issues, which is why I'm submitting an issue instead of a pull request is:

1. Do all OAuth 2 implementations return `{"error": "invalid_grant", "error_description": "Refresh token expired"}` when the refresh token is expired?
2. We might need an escape hatch in the code in-case something screwy is happening with the auth server.  Imagine having an expired refresh token, making a request with it, getting a response indicating it's expired, attempting to re-auth, then getting a 401 response.  Could you get stuck in a loop constantly trying to re-auth?

**Comment by Lavoaster** [comment]
I actually submitted #1729 because of this thing. It’s really annoying!

I haven’t tested what an auth failure loop might look like but I don’t believe this is susceptible to it as the code only gets run on if there’s a token available to refresh.

**Comment by gschier** [comment]
Yep, I think this is fixed now
