### ISSUE TITLE
[Bug] v7.0.3 stop working with "Library not loaded: /usr/local/php5/lib/libssh2.1.dylib"

### ISSUE THREAD

**Issue by emanueledona** [Kong/insomnia#1754]
- Insomnia Version: 7.0.3
- Operating System: Mac OS Catalina 10.15

## Details

From nowhere Insomnia stop working, yesterday (10/26/19) it works fine.

This is the current error reported : 
![image](https://user-images.githubusercontent.com/769518/67617948-d20c3700-f7e8-11e9-897e-e772f5ad805f.png)

I have tryed a fresh install downloading the DMG and, again, using the brew command but nothing change.

I have a php 7.x installation with brew; but all works fine before today.

**Comment by Bosbaba** [comment]
I'm experiencing the same issue, on opening Insomnia it throws this error
Insomnia Version: 7.0.3
Operating System: Mac OS Mojave 10.14.6

![image](https://user-images.githubusercontent.com/3582296/67861054-128ced00-fb28-11e9-93c2-70d77c2d706c.png)

**Comment by Bosbaba** [comment]
Same issue as [#1743](https://github.com/getinsomnia/insomnia/issues/1743)

**Comment by filfreire** [comment]
Hi folks, I'm going to go ahead and close this one since it's been a while, but feel free to report a new issue if you are still getting this error in one of our [latest Insomnia versions](https://github.com/Kong/insomnia/releases)
