### ISSUE TITLE
[Bug] Insomnia (7.0.3~7.1.0) show white screen on macOS 10.15

### ISSUE THREAD

**Issue by jerryzhoujw** [Kong/insomnia#1755]
- Insomnia Version: 7.0.3
- Operating System: macOS 10.15

## Details

After open Insomnia, it keep show white screen, nothing else.

<img width="610" alt="Screen Shot 2019-10-28 at 9 29 54 PM" src="https://user-images.githubusercontent.com/6405390/67682393-3afed500-f9ca-11e9-886b-aea5ab9398bb.png">

**Comment by gschier** [comment]
Do you see anything in View > Toggle DevTools > Console?

**Comment by jerryzhoujw** [comment]
it seems because of https://api.insomnia.rest/graphql?projects not returned.

<img width="818" alt="Screen Shot 2019-10-28 at 10 23 49 PM" src="https://user-images.githubusercontent.com/6405390/67732312-dd07d700-fa35-11e9-89ac-2f5da358f5cd.png">
<img width="804" alt="Screen Shot 2019-10-28 at 10 24 18 PM" src="https://user-images.githubusercontent.com/6405390/67732313-dd07d700-fa35-11e9-9070-5c9840e0e091.png">

**Comment by gschier** [comment]
That's strange that that endpoint doesn't return. Are you behind a corporate proxy by any chance? Can you try right clicking the request, copy as Curl, and running it from your command line to see if you get something similar?

**Comment by jerryzhoujw** [comment]
> curl 'https://api.insomnia.rest/graphql?projects' -H 'Origin: null' -H 'X-Session-Id: 8dabb53305daba1b02e5c7f8f7ba8ae0731a4ef822f633ddeac89452971b2229' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Insomnia/7.0.3 Chrome/66.0.3359.181 Electron/3.1.13 Safari/537.36' -H 'X-Insomnia-Client: production::darwin::7.0.3' -H 'Content-Type: application/json' --data-binary '{"query":"\n        query {\n          projects {\n            id\n            name\n            rootDocumentId\n          }\n        }\n      ","variables":{}}' --compressed
{"data":{"projects":[]}}

**Comment by Bosbaba** [comment]
I have the same issue, but don't even get that far. Getting a blank screen on sending a request

![Screenshot 2019-11-04 at 09 12 25](https://user-images.githubusercontent.com/3582296/68105126-3bc1ca80-fee6-11e9-9eae-fd3ddbd8e009.png)

**Comment by jerryzhoujw** [comment]
@Bosbaba  I just close the popover of `DevTools was disco...`, and click `Cmd` + `R`

**Comment by Bosbaba** [comment]
@jerryzhoujw that just reload my page to the state it was in before sending the request. But I've got a feeling it is related to the bug mentioned in [#1743](https://github.com/getinsomnia/insomnia/issues/1743) and [#1754](https://github.com/getinsomnia/insomnia/issues/1754)

**Comment by jerryzhoujw** [comment]
This issue is solved by `complete delete the Insomnia app` and it's related file (which make sure it's `logout status` when I install a new Insomnia), and install latest app: `Insomnia 7.0.5`

PS: there's 2 error when I open the new app, and login again.

<img width="971" alt="Screen Shot 2019-12-02 at 2 32 03 PM" src="https://user-images.githubusercontent.com/6405390/69935769-cfe87700-1510-11ea-9917-8f0eb06a7748.png">

**Comment by jerryzhoujw** [comment]
After used for a while, maybe several hours, this issue appear again.


![Dec-02-2019 17-07-11](https://user-images.githubusercontent.com/6405390/69946251-42178680-1526-11ea-86a5-14006309506f.gif)

**Comment by awilkins** [comment]
I also had this on first opening. (7.0.5, Ubuntu 18.04, tried both the snap and deb installs).

Resolved with the workaround above - open the dev console and hit ctrl-R. Then it loads on opening (there's a moment of white screen before the UI loads).

If you delete `~/.config/Insomnia` this recurs, so I'm guessing it's something triggered by initial configuration.

**Comment by prokher** [comment]
> I also had this on first opening.

I had the same. After restart it has started normally.

**Comment by gschier** [comment]
This was fixed yesterday and will be in the next release

**Comment by jerryzhoujw** [comment]
wow great news @gschier thank you.

**Comment by jerryzhoujw** [comment]
It still happened with 7.0.6 @gschier

**Comment by jerryzhoujw** [comment]
can I reopen this ? @gschier

**Comment by jerryzhoujw** [comment]
is that possible because of duplicate name workspace ?

<img width="228" alt="Screen Shot 2019-12-19 at 1 21 59 PM" src="https://user-images.githubusercontent.com/6405390/71147682-739d8b00-2264-11ea-8649-c22f20a5ee3f.png">

**Comment by gschier** [comment]
Hmm, ya there was a race condition that I fixed but perhaps there's an edge case that it didn't cover.

Would you be able to go to Help > Show AppData Folder, create a backup of the folder, then delete the folder and relaunch the app? I'm curious if it still happens with fresh data.

**Comment by gschier** [comment]
Also, thanks for the Gif, it helps a lot! 

Also also, no the workspace names shouldn't have an impact. They are simple used for display purposes.

**Comment by jerryzhoujw** [comment]
@gschier  After test: remove data -> login again -> after sync for a while, open a request will become white window again.

**Comment by keepanitreel** [comment]
Hello everyone I have been having this issue for 6 months and tonight I was able to figure it out.

CURL is most likely your problem . Mac OS was running 7.47 (Apple's version). I used home brew to install the lates (7.68) then added it to my profile path (.bash_profile) (your not allowed to link over os provided stuff) NOW IT WORKS. SO happy. It has been a struggle with out Insomnia for 6 months. I hope this helps everyone!!!

**Comment by jerryzhoujw** [comment]
Mine `curl` is `7.41.0`

> curl --version

```sh
curl 7.41.0 (x86_64-apple-darwin14.0.0) libcurl/7.41.0 OpenSSL/1.0.2a zlib/1.2.8 libidn/1.29
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

**Comment by jerryzhoujw** [comment]
Hi  @keepanitreel,

> brew install curl -verbose

will install `curl 7.67.0 (x86_64-apple-darwin19.2.0) libcurl/7.67.0 SecureTransport zlib/1.2.11 libidn2/2.3.0` 

After config in `.bashrc` file with `PATH="/usr/local/opt/curl/bin:$PATH"`,

and enable it with `. ~/.bashrc`.

and open the Insomnia again, it's not fix this issue.

**Comment by maciejzukowski** [comment]
I am getting the same issue on mac 10.15.3 and Insomnia 7.1.0.  I've tried clearing app data, reinstalling Insomnia, and updating curl.  No errors in DevTools.  Happens right when i click send on any request.

**Comment by maciejzukowski** [comment]
Running the application from terminal gave me the following error when i try to perform any request.

`Insomnia Helper(73249,0x1137c9dc0) malloc: *** error for object 0x7ffa9c1b0658: pointer being freed was not allocated
Insomnia Helper(73249,0x1137c9dc0) malloc: *** set a breakpoint in malloc_error_break to debug
[73248:0409/120900.670265:ERROR:gles2_cmd_decoder.cc(18288)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[73248:0409/120900.670721:ERROR:gles2_cmd_decoder.cc(12419)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[73248:0409/120900.670742:ERROR:gles2_cmd_decoder.cc(18288)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[73248:0409/120900.670752:ERROR:gles2_cmd_decoder.cc(12419)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[73248:0409/120900.670764:ERROR:gles2_cmd_decoder.cc(18288)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[73248:0409/120900.670776:ERROR:gles2_cmd_decoder.cc(12419)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[73248:0409/120900.671157:ERROR:gles2_cmd_decoder.cc(12419)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[73248:0409/120900.671180:ERROR:gles2_cmd_decoder.cc(12419)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[73248:0409/120900.671198:ERROR:gles2_cmd_decoder.cc(18288)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[73248:0409/120900.671214:ERROR:gles2_cmd_decoder.cc(12419)] [.DisplayCompositor-0x7fd5c3063000]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format`

**Comment by noplanman** [comment]
I'm having the same issue with version 2020.2.1. Like @maciejzukowski I ran `/Applications/Insomnia.app/Contents/MacOS/Insomnia` from console and saw this as the white screen occurs.
```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /var/folders/kg/mlmb3t0x67q7s_33kfhfkwbw0000gn/T/.com.insomnia.app.kVKqHe (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /var/folders/kg/mlmb3t0x67q7s_33kfhfkwbw0000gn/T/.com.insomnia.app.kVKqHe (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

Looks like the latest versions are MacOS 10.12+? Would be nice if the auto-updater would take that into account.

**Comment by ghinazi** [comment]
any updates on this?

**Comment by DMarby** [comment]
Insomnia requires macOS Sierra (10.12) or newer to function correctly, if you're having issues and are running an older macOS version then 10.12, please **update your computer** to **at least** macOS Sierra (10.12).

If you are using a more recent macOS version (10.12 or newer) and are having issues, please update your Insomnia app to the latest version.

If you're still seeing issues with a white screen while on macOS 10.12 and newer, and are using the latest version of Insomnia, please open a new GitHub issue.
