### ISSUE TITLE
[Feature Request] Allow the name of the environment to be used as a variable

### ISSUE THREAD

**Issue by Tarig0** [Kong/insomnia#1771]
- Insomnia Version: 7.0.3
- Operating System: Windows 10 x64

## Details
Small - QOLI
I have setup a few environments with a variable that is literally the name of sub environment.
maybe using the macro {% environment %}

For example {"baseUrl": "www{% environment %}.mydomain.com", "environment":"DevA"}

**Comment by elemanhillary** [comment]
Not detailed

**Comment by rafaelrenanpacheco** [comment]
This feature is way too specific and would make sense just for those with that exactly environment situation. A simple (and already supported) solution is, for each environment, to add a field with the same value as your environment.

A simple, and already supported solution, is just do:

```json
{"baseUrl": "wwwDevA.mydomain.com"}
```

And change that for each environment.

**Comment by Tarig0** [comment]
This feature has been requested multiple times, so I don't think it is specific. I see this as an extension of the request => folder which is able to go as high as the workspace name.

**Comment by gschier** [comment]
I think this would be nice to have. We could have an environment tag with operations to do things on the current environment, one of them being to get the name

**Comment by Tarig0** [comment]
Do we have any other idea's on what could be done on the current environment?
