### ISSUE TITLE
[Feature Request] Scriptable attributes

### ISSUE THREAD

**Issue by Valve** [Kong/insomnia#1777]
Thanks for Insomnia, it's a very good tool!

I was wondering if you had scriptable JSON values planned.

Before:

```
{
   "name": "John",
   "timestamp": 1573576033
}

```

After:

```
{
   "name": "John",
   "timestamp": {{ Date.now() }}
}
```

My use case: I'm testing an API that I'm developing and it needs to always have a current (or relatively fresh) timestamp field, which I have to update manually every time.
Thanks!

**Comment by gschier** [comment]
Yep, you can already do this 😄 https://support.insomnia.rest/article/40-template-tags

Also see the eval plugin if you want to literally write JS scripts https://www.npmjs.com/package/insomnia-plugin-js-eval
