### ISSUE TITLE
[Feature Request] Ability to access non-text body content from plugin context

### ISSUE THREAD

**Issue by davidhampson** [Kong/insomnia#1788]
- Insomnia Version: v7.0.3
- Operating System: Windows 10
## Details

Writing a plugin to authenticate an API, need to MD5 hash the body content, and context.request.getBodyText() returns an empty string for request bodies that aren't just text (form, multipart form, etc).
Couldn't find any alternative function calls to access the body object that contains the field data, unless I am mistaken this seems like a gap in the API.

Thanks!

**Comment by kreosus** [comment]
Hi @davidhampson,
Thank you for bringing this to our attention. Have you been able to reproduce it on our newest release, located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.2
