### ISSUE TITLE
[Feature Request] Add support for Linux via Flatpak

### ISSUE THREAD

**Issue by dumindu** [Kong/insomnia#1812]
[Flatpak](https://flatpak.org/) is a next-generation collaborative technology for building and distributing desktop applications on Linux and it's having much open ecosystem than Canonical's Snap. Please support for Linux via Flatpak and [Flathub](https://flathub.org/home)

Related issues, PRs and docs:
- https://github.com/getinsomnia/insomnia/issues/939
- https://github.com/flathub/flathub/pull/504
- http://docs.flatpak.org/en/latest/getting-started.html

Thanks

**Comment by gschier** [comment]
Thanks for the suggestion! Please see https://github.com/electron-userland/electron-builder/issues/512 for status

**Comment by doums** [comment]
Any news ???

**Comment by dumindu** [comment]
@gschier That's a 4 years old issue without any active movement. 
How you guys support Ubuntu's Snap then?

**Comment by nblackburn** [comment]
Related #939

**Comment by rocketraman** [comment]
Looks like https://github.com/electron-userland/electron-builder/issues/512 is now resolved.

**Comment by reynolek** [comment]
At this point we are not planning to support Flatpak. This may change in the future, but with Snap, a debian/ubuntu repo, and github packages available to download, we feel we offer enough ways to install for Linux for the time being.

**Comment by WhyNotHugo** [comment]
Would you mind a community maintained Flatpak package? (i.e.: do you mind if I submit one to Flathub?).

FWIW, it seems odd to maintain Snap _and_ Ubuntu repo, since they both target mostly one same audience (Canonical/Ubuntu). Maybe you'd want to consider dropping Snap in favour of Flatpak (the latter having support in a lot of distros)?

**Comment by dimitropoulos** [comment]
> [me] enters flathub.com into my browser
> [me. moments later] nope.

Well, being friendly to Linux users is definitely top of mind for us (I'm a Linux user, for example).  I've never used flatpack but I can say that we've had trouble with snap (including snap-specific bugs) in the past, and I think that's what contributes to wanting to tone this down just a bit.

How does it work? If we create a flatpack package and then give you access? There seems to be a process for us to take control of it (https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do) if we ever want to take-over control of it so maybe it's fine that you make one?  Please advise.

**Comment by stephenmoloney** [comment]
> > [me] enters flathub.com into my browser

https://flathub.org/home

I would second flathub. I've abandoned snap since quite some time ago.

**Comment by WhyNotHugo** [comment]
I have a sample manifest here: https://github.com/WhyNotHugo/rest.insomnia.client

The readme explains how to build a flatpak based on that. Here's some caveats:

- I don't remember if Insomnia actually uses notifications. If not, it might be fine to [drop that permission](https://github.com/WhyNotHugo/rest.insomnia.client/blob/0017833/rest.insomnia.client.yml#L16).
- The published tarball only has a 1024x1024 icon, but that largest supported by flatpak (and Linux desktop in general really) is 512x512. I've worked around this by leaving a smaller icon in-repo.
- The published tarball has no `.desktop` file, so I've put one in-repo. I've based it on the one used by the ArchLinux package. It's be great if it could be included in the tarball though, so all downstreams can re-use the same one.

I can open a PR in https://github.com/flathub/flathub if that's okay with you, and tag you in it to keep you posted (and so you're also included as maintainers).

Lemme know if you're okay with that.

**Comment by rocketraman** [comment]
@WhyNotHugo FYI your repo worked for me to build a flatpak for Insomnia locally, thank you! For others who might be interested, the complete build instructions were:

```
flatpak install org.freedesktop.Sdk//20.08
flatpak install org.electronjs.Electron2.BaseApp//20.08
# as per README
flatpak-builder --user --install build-dir rest.insomnia.client.yml --force-clean
```

**Comment by rocketraman** [comment]
@WhyNotHugo are you still planning to open a PR at flathub/flathub?

**Comment by WhyNotHugo** [comment]
I've opened it here: https://github.com/flathub/flathub/pull/2406

@dimitropoulos As a contributor here, please let me know if you have any comments on this.

**Comment by WhyNotHugo** [comment]
A community-maintained package has been published: https://flathub.org/apps/details/rest.insomnia.Insomnia

Please keep in mind this is **not** an official package, so any packaging issues, please report at https://github.com/flathub/rest.insomnia.Insomnia
