### ISSUE TITLE
[Feature Request] Add option to disable URL clickthroughs in Preview results

### ISSUE THREAD

**Issue by BadPackets** [Kong/insomnia#1817]
It would be nice to have a feature to disable URL clickthroughs in Preview results section.

Reason: We use Insomnia to test our REST API, which provides cyber threat intel, and it frequently contains payloads with URIs pointing to malicious (C2) servers. If there was an option to disable URL clickthoughs, it would prevent the user from accidently clicking on a malicious link.

![image](https://user-images.githubusercontent.com/32589462/69826057-583fe280-11c6-11ea-9d4e-bd202c498c2d.png)

**Comment by gschier** [comment]
This seems like a good thing to have. A few users have also complained about clicking them by accident when trying to select/copy.

**Comment by elemanhillary** [comment]
am working on this, wats remaining is mocking the data, so that i can get response with url clickthrough enabled

**Comment by gschier** [comment]
@elemanhillary awesome!

Insomnia has a simple echo endpoint you can use to test. Try importing this command by pasting it into the Insomnia URL bar

```
curl --request POST \
  --url https://api.insomnia.rest/mock/echo \
  --header 'content-type: application/json' \
  --data '{
	"url": "https://insomnia.rest"
}'
```

**Comment by elemanhillary** [comment]
@gschier am unable to get a response with URL clickthrough enabled, with the provided curl you gave me

**Comment by elemanhillary** [comment]
@BadPackets what version of insomnia are you using and @gschier were you able to reproduce the issue cause me I can't it's validated without a clickthrough

**Comment by elemanhillary** [comment]
@gschier and @BadPackets running from development, it's impossible to reproduce the error, it's only possible on the production version. why?

**Comment by elemanhillary** [comment]
OMG @gschier  and @BadPackets sorry, I was already in my branch and the feature I have implemented had disabled URL
<img width="1059" alt="Screen Shot 2019-12-12 at 14 57 47" src="https://user-images.githubusercontent.com/14273401/70713924-c53b9800-1cef-11ea-887e-9b3baa86fb97.png">
 click-throughs. my bad

**Comment by tmursch** [comment]
@gschier When will this be available in the production version of Insomnia?
![image](https://user-images.githubusercontent.com/32589462/74269201-fae40980-4cbd-11ea-9c2d-af543abef3c7.png)
![image](https://user-images.githubusercontent.com/32589462/74269286-14855100-4cbe-11ea-9d25-c7f26e048898.png)
