### ISSUE TITLE
[Feature Request] Hooks/schedule based api calls

### ISSUE THREAD

**Issue by knomdlo** [Kong/insomnia#1818]
- Insomnia Version: Latest
- Operating System: All

## Details

Can we have a feature wherein a configuration can be provided to run a few calls on env switch/ schedule.

Use case:
  **Env switch hook**:
 Our apps using Oauth token based authorizations. Every time we switch an environment, we'll have to make the token call for the respective env.

  **Scheduler**
As token expires every few minutes, we need to make a refresh token call to re validate it.

**Comment by filfreire** [comment]
Hello @knomdlo, thanks for reporting this and sorry for not getting back to you in a while!

I would suggest you use our [Request Chaining](https://docs.insomnia.rest/insomnia/chaining-requests) feature to do this kind of thing.

![Image](https://user-images.githubusercontent.com/11976836/181253088-f05f36f7-d3d0-4ccc-a666-cffdc640d8bb.png)
![Image](https://user-images.githubusercontent.com/11976836/181253176-18adf044-ab97-4a92-bb77-232ffc713863.png)

Feel free to report any other issues or ideas you may have!
