### ISSUE TITLE
[Help] Generated Code doesn't work

### ISSUE THREAD

**Issue by CAIOHOBORGHI** [Kong/insomnia#1823]
Hello, I'm having trouble trying to use the "Generate Code" function... The code provided doesnt return the same result that Insomnia do... I get always an empty response... Tryed with curl and NodeJS(HTTP and Request) Snippets but none of them work... I've noticed that in "Timeline" Insomnia is showing > GET / HTTP/1.1 3 different times but the generated code gives me only one, and the cookies differs too (Cookie tab has 3 and code has only 1)

Can u guys help me?

**Comment by gschier** [comment]
Can you please provide an example to reproduce the problem?

Just as a note, the code generation feature does not guarantee it will work the same as within Insomnia.

**Comment by CAIOHOBORGHI** [comment]
Yes I can. For example, the GET Request on https://nike.com
Even thought the first http request returns 301(Moved Permanently) as observed on timeline, the generated code to node or curl does not work... 
Is there any way to replicate the steps Insomnia makes to retrieve the HTML data? 


![image](https://user-images.githubusercontent.com/19851187/70074781-2d94c600-15da-11ea-91b3-1c56db4c10c0.png)

**Comment by gschier** [comment]
I think the problem is that Node and libcurl do not automatically follow redirects. You'll have to look up how to do that. 

For Curl, adding the `--location` will enable it.
