### ISSUE TITLE
[Bug] Cannot pull remote workspace (Beta version control)

### ISSUE THREAD

**Issue by natepisarski** [Kong/insomnia#1828]
- Insomnia Version: 7.0.5
- Operating System: Manjaro Linux, Mac OS

## Details

My team and I all had the Version Control beta turned on. We were all able to create and push snapshots. However, none of us would see the changes that the other made. Whenever I click the Remote Workspaces dropdown and click "Pull **Adventuresoft**", I get the following error message: [IMGUR](https://i.imgur.com/5IYsU8k.png)

## Extra Information

* This workspace was originally created before any of us had the version control beta on.
* We only have one branch: master.
* Sometimes, the pull will appear to work. However, I can't see my teammate's changes, even when it seems like it works.

**Comment by gschier** [comment]
Hmm, it might be because you had been sharing it before you configured sync. 

Can you try duplicating the workspace (will generate new IDs), enabling sync, and sharing that new one with your team? That way it will have a fresh place to start from.

**Comment by natepisarski** [comment]
@gschier you were absolutely correct. We had no trouble once we created a new workspace. I'll leave the issue open since there's still a problem somewhere. Let me know if you want any more info to try and reproduce this.

**Comment by gschier** [comment]
I'm glad the workaround worked. 

During the initial setup, did each member enable sync of the workspace and share with each other? If so, this would have created multiple sync references to the same workspace with different encryption keys for each one.

I feel like the appropriate solution is to detect if multiple sync projects point to the same workspace and providing a UI to allow the user to chose the "official" one.

**Comment by natepisarski** [comment]
Yes, we have a group/Team called "AdventureWorks Developers". All of our users were sharing the workspace with this team at the time. For a few days one of the developers had "manual sync" enabled. Other than that, it was all automatically synced. Also, once we all turned the beta off, our syncing with one another seemed to go on as usual.

**Comment by gschier** [comment]
Thanks for the info. It helps a lot 🙂

**Comment by natepisarski** [comment]
@gschier Just to add a bit more context for this, we made the new workspace and all is well. However, every person on the team sees "Pull [WORKSPACE]" under "Remote Workspaces". None of us can actually pull it, though. Also, according to the team lead, "[WORKSPACE]" cannot be deleted - not even from the website. It's not super disruptive, but there's definitely something wrong here.

**Comment by gschier** [comment]
Ah yes, there's no way to delete a remote sync project right now. If you send an email over to support@insomnia.rest with your account details I can delete it for you.

**Comment by DMarby** [comment]
Hi @natepisarski,

We just released 2020.4.2 which contains a number of fixes for issues related to the version control beta sync, including this one.

Please give it a try, and if you're still having issues, send us an email at support@insomnia.rest so that we can best assist you with these issues!
