### ISSUE TITLE
Show deprecation warning and message in GraphQL schema explorer

### ISSUE THREAD

**Issue by pingvinen** [Kong/insomnia#1831]
- Insomnia Version: 7.0.5
- Operating System: Ubuntu 18.04

## Details

I noticed that the GraphQL editor has an awesome deprecation-warning built-in, but the deprecation warning is not shown in the schema explorer. I think that would be a nice edition - preferably with a big fat warning icon :)

**Comment by gschier** [comment]
Oh, good idea!

**Comment by elemanhillary-zz** [comment]
@pingvinen, I like it with examples cause I have never seen any deprecation warning in the GraphQL editor. I can work on that if given steps to produce a deprecation warning. Thanks

**Comment by briskt** [comment]
@elemanhillary thanks for offering to work on this. The spec is [here](https://github.com/graphql/graphql-spec/blob/master/spec/Section%203%20--%20Type%20System.md#deprecated).

**Comment by antoine29** [comment]
Hey @gschier @nijikokun 
I'm checking this issue. I hope is not too late :D
