### ISSUE TITLE
Text Editor Font is incomplete

### ISSUE THREAD

**Issue by iiinsomnia** [Kong/insomnia#1835]
- Insomnia Version: v7.0.5
- Operating System: macOS 10.15.1

## Details

![image](https://user-images.githubusercontent.com/6582246/70590074-8680e180-1c0c-11ea-852b-db09df385101.png)

### Interface Font

![image](https://user-images.githubusercontent.com/6582246/70590119-aca68180-1c0c-11ea-8dd6-127f7817939e.png)

### Text Editor Font

![image](https://user-images.githubusercontent.com/6582246/70590135-b9c37080-1c0c-11ea-815e-45c7b5492ba7.png)

**Comment by gschier** [comment]
Can you explain what you mean by "Incomplete?" The text editor font selector only show fixed-width fonts. Is that what you are pointing out?

**Comment by iiinsomnia** [comment]
The font 'Fixedsys Excelsior' which I want is not in the selector 💔

**Comment by gschier** [comment]
Ah, let me see if I can figure out why
