### ISSUE TITLE
Broken icon on Xubuntu 18.04

### ISSUE THREAD

**Issue by krasoffski** [Kong/insomnia#1837]
Thank you for great application.

Despite the fact that there is closed issue #1717 I am opening new one related problem on XFCE or XUbuntu. Moreover solution steps from parent issue did not help.

- Insomnia Version:
![image](https://user-images.githubusercontent.com/1073415/69874208-79d6c200-12cb-11ea-9ee9-c8927b923381.png)
![image](https://user-images.githubusercontent.com/1073415/70616265-14fe5e80-1c1f-11ea-9ce7-12a071cacd9d.png)

- Operating System:
```
~ $ cat /etc/issue
Ubuntu 18.04.3 LTS \n \l
```

**Comment by gschier** [comment]
What installation method did you use?

**Comment by krasoffski** [comment]
Hi,
Installed via ppa using deb and tested with archive `tar.gz`

**Comment by ghost** [comment]
I have xubuntu 19.10 and installed Insomnia from the snap store and I have the same problem.
The Icon in the application finder is fine, but not in the panel (the icon between firefox and spotify)

![image](https://user-images.githubusercontent.com/10061147/72894423-9582a580-3d1b-11ea-88c4-ab6bb9c76771.png)

The start command:
`env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/insomnia_insomnia.desktop /snap/bin/insomnia`

The .deskop file:
```
[Desktop Entry]
X-SnapInstanceName=insomnia
Name=Insomnia
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/insomnia_insomnia.desktop /snap/bin/insomnia
Terminal=false
Type=Application
Icon=/snap/insomnia/55/meta/gui/icon.png
StartupWMClass=Insomnia
Comment=Debug APIs like a human, not a robot
MimeType=x-scheme-handler/insomnia;
Categories=Development;
```

And the icon seems fine:
`feh /snap/insomnia/55/meta/gui/icon.png`

Maybe the icon is just not found?
`icon: path.resolve(__dirname, 'static/icon.png'),`

**Comment by mrf345** [comment]
Hello, I'm having a similar issue running `Xfce4` on `Manjaro 19.0`:

![image](https://user-images.githubusercontent.com/26286907/75121604-9b670000-56a6-11ea-9a9e-c9b1d4ffc153.png)

**Comment by rmharrison** [comment]
![Insomnia_Ico](https://user-images.githubusercontent.com/4275722/80651930-d984f500-8a44-11ea-8c38-9459118d6633.png)

**CORE/REST**
Verified ico.
Ubuntu 19.10 via snap (V7.1.1)

**Designer**
No ico.
Ubuntu 19.10 via [`.deb`](https://github.com/Kong/insomnia/releases/tag/designer%402020.1.3) (designer@2020.1.3)

**Comment by rst5nn** [comment]
I see icon now in panel:
![image](https://user-images.githubusercontent.com/1073415/88270530-75d63500-ccde-11ea-8d49-f29569c2d183.png)

But not sure this is correct one.

Version:
![image](https://user-images.githubusercontent.com/1073415/88270605-90a8a980-ccde-11ea-8e33-3403b65f6f0d.png)

**Comment by rst5nn** [comment]
Still awaiting fix.

**Comment by filfreire** [comment]
Hi @krasoffski, are you still able to reproduce this issue with our [latest stable release](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2)?

**Comment by rst5nn** [comment]
Hi @filfreire 

Xubuntu 18.04 EoL is coming and I moved to Xubuntu 20.04. 
Regarding to issue, I think we can close it as it works without problems on 20.04.

**Comment by filfreire** [comment]
@krasoffski nice! 🎉 

Feel free to report any other issues you find.
