### ISSUE TITLE
Insomnia went completely blank

### ISSUE THREAD

**Issue by ToAruShiroiNeko** [Kong/insomnia#1838]
This has just started on multiple windows computers (Windows 10 & Windows Server 2016) where Insomnia screen is white without options. I am unsure how to deal with this.

![image](https://user-images.githubusercontent.com/7820084/70640124-c4e1c500-1c3b-11ea-9c94-05fc764ed64e.png)

**Comment by gschier** [comment]
Do you see any errors when visiting View > Toggle DevTools > Console?

**Comment by gschier** [comment]
It could be similar to [this one](https://github.com/Kong/insomnia/issues/1833) which has been fixed but not yet released.

**Comment by ToAruShiroiNeko** [comment]
Certainly, I have attached the screenshot.

![image](https://user-images.githubusercontent.com/7820084/70698673-3f582680-1cc8-11ea-94e1-63d36c0a209c.png)

**Comment by lbenka** [comment]
![Screenshot 2019-12-12 at 11 53 17](https://user-images.githubusercontent.com/17259090/70706441-32423400-1cd6-11ea-9281-15b518d683ec.png)

Same over here

**Comment by arturhun** [comment]
Mac 10.15, Insomnia 7.0.5.3191
Created a new workspace and Insomnia went blank, DevTools showed the following error

![image](https://user-images.githubusercontent.com/42932011/70816561-0c995580-1dd0-11ea-8b82-6b92b7249791.png)

**Comment by gschier** [comment]
@arturhun this one was fixed a few days ago but hasn't been deployed yet.

**Comment by nijikokun** [comment]
@lbenka do you mind taking another screenshot with the "Console" tab open in developer tools 💖

**Comment by lbenka** [comment]
Sorry for the delay 
<img width="1139" alt="Screenshot 2020-01-06 at 20 50 39" src="https://user-images.githubusercontent.com/17259090/71844374-448d7300-30c6-11ea-9080-f1bc803004fc.png">

**Comment by lbenka** [comment]
I had some problems with curl and openssl on my mac, not sure if that could be related

**Comment by noplanman** [comment]
@lbenka Care to elaborate? I'm running into the same issue and was wondering if maybe curl or openssl could be the problem. Thanks!

**Comment by fredngo** [comment]
Duplicate of https://github.com/Kong/insomnia/issues/1940 ? This is really terrible as I can't use Insomnia anymore... I don't wanna use Postman :(

**Comment by noplanman** [comment]
I just ended up staying on version 7.1.\*, as the problem only started with the newer 2020.\* versions.
Not a "solution", but at least I can carry on using Insomnia :innocent:

**Comment by wongstein** [comment]
Closing this issue as it seems to have been resolved a couple of versions ago.
