### ISSUE TITLE
No history option available

### ISSUE THREAD

**Issue by santosh-hegde** [Kong/insomnia#1844]
Insomnia is a good alternate for Postman, one of the main features I'm missing is History.

It would be great if we have that option as well.

**Comment by gschier** [comment]
History is broken down per-request and can be found at the top-right of the response pane

<img width="461" alt="image" src="https://user-images.githubusercontent.com/587576/70725468-6c0d3d80-1cca-11ea-83ce-49388187bcf9.png">
