### ISSUE TITLE
[Build] Update Electron

### ISSUE THREAD

**Issue by gschier** [Kong/insomnia#1847]
The version of Electron we're on is now quite out of date. We should update to the latest.

The OAuth 2.0 dialog is already starting to fail due to the outdated user-agent of our app's Chromium build https://github.com/Kong/insomnia/issues/1774

## Issues Discovered

- [x] compiling font manager breaks
  - [x] Try upgrading [`font-scanner`](https://github.com/axosoft/font-scanner) 
  - [ ] ~~Switch to a JS-only implementation like [`get-system-fonts`](https://github.com/princjef/get-system-fonts)~~
- [ ] compiling [`node-libcurl`](https://github.com/JCMais/node-libcurl) breaks
  - [ ] Try updating `node-libcurl`
- [ ] compiling `fsevents` fails

**Comment by semoal** [comment]
Actually for me, with lts node version, i cant even start the project in my local machine.

I can look at this if you want :+1:

**Comment by gschier** [comment]
Going to call this issue done as a first try. Will move progress to the newer https://github.com/Kong/insomnia/issues/2369
