### ISSUE TITLE
[Bug] Multiple windows not prevented on Windows/Linux

### ISSUE THREAD

**Issue by gschier** [Kong/insomnia#1849]
See #1763 for original report.

Currently, Insomnia does not support operating in a multi-window environment since database updates are not synchronized between them. We should disable this feature and then properly implement #667 to enable full multi-window support.

**Comment by kreosus** [comment]
Closing as a duplicate of https://github.com/Kong/insomnia/issues/667 . This feature is not currently on the roadmap, but hope to add it soon.
