### ISSUE TITLE
[Feature Request] Beautify JSON improvements

### ISSUE THREAD

**Issue by arturhun** [Kong/insomnia#1851]
The **Beautify JSON** button/functionality could:
- be capable of removing trailing commas
- be capable of fixing/escaping quotes
- be available in prefs for keyboard mapping

**Comment by hellp** [comment]
+1 for having a keyboard shortcut for Beautify. Maybe this should be a separate issue. I imagine it easier to do than the first two bullet points.

**Comment by gschier** [comment]
I agree with @hellp about creating a separate issue.

It seems that there are two suggestions here:

1. Allow beatify to fix common errors
2. Add a keyboard shortcut for beautify

**Comment by joel-daros** [comment]
+1 for having a keyboard shortcut for Beautify.

**Comment by seanghay** [comment]
+1
