### ISSUE TITLE
[Bug] Blank White Screen on First Startup

### ISSUE THREAD

**Issue by kevin-hv** [Kong/insomnia#1852]
**Describe the bug**
After installation a white screen appears, and the application does not load its UI elements.

**To Reproduce**
Install the application via brew cask
Start the application from Spotlight search

**Expected behavior**
The application to load fully, and greeted with a user interface.

**Screenshots**
Besides the blank view, if I click on View -> Toggle DevTools gives the following error messages, that are visible on the screenshot below. (Unfortunately I haven't taken more)
<img width="655" alt="Screenshot 2019-12-12 at 17 40 00" src="https://user-images.githubusercontent.com/44970281/70850088-b76c4b00-1e86-11ea-9e40-1fafc48fc267.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.1 (Catalina)
 - Installation Method: homebrew cask
 - App Version V7.0.5

**Additional context**
After quitting the application with Command + Q and starting it again it presented itself with the following view, I believe this is also what should have been presented on first startup and now it works as it should.
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/44970281/70850125-13cf6a80-1e87-11ea-81c6-17f2b3a36d35.png">

**Comment by art-in** [comment]
Same for me after install and after creating new workspace in window 10.

![57566c45127478a28715dd5b05641ad0](https://user-images.githubusercontent.com/671082/71000724-d10ecc00-20ec-11ea-8ba2-adf21414b15f.png)

**Comment by gschier** [comment]
This was fixed a few days ago. Will be releasing a new version with the fix shortly!
