### ISSUE TITLE
[Feature Request] Export a single request

### ISSUE THREAD

**Issue by LilSebastian5000** [Kong/insomnia#1860]
**Is your feature request related to a problem? Please describe.**
It's frustrating that you have to create an entirely new workspace to add just a single request when you don't want to export an entire workspace for a coworker. 

**Describe the solution you'd like**
It would be nice to be able to export one single request at a time by just right-clicking it instead of only being able to export at the workspace level :)

**Additional context**
There already was an existing issue, but it was closed for some reason. This seems like a no-brainer and just want to make sure it's still something that the team is aware of due to being closed: https://github.com/Kong/insomnia/issues/538

**Comment by gschier** [comment]
Reopened the old issue

Duplicate of #538
