### ISSUE TITLE
[Bug] "Do not notify of new releases" setting is ignored

### ISSUE THREAD

**Issue by shroudedcode** [Kong/insomnia#1862]
Enabling the *Do not notify of new releases* setting doesn't do anything.

**How to reproduce:**

1. Open the preferences modal
2. Enable *Do not notify of new releases*
3. Restart the app after a new release
4. See the *Updated to X.X.X* notification pop up

**Expected behavior:**

The notification should not be shown.

**Desktop:**

 - OS: Ubuntu 19.10
 - Installation Method: Debian package
 - App Version: 7.0.6

**Additional context:**

The setting seems to be [set](https://github.com/Kong/insomnia/blob/e485d55aea4fd2edf09088feeecb4d19a1c75d7f/packages/insomnia-app/app/ui/components/settings/general.js#L406-L410) but not [used where it should be used](https://github.com/Kong/insomnia/blob/b70018a9aa862961e690c0ec65f9e9c3c2c27d13/packages/insomnia-app/app/main.development.js#L137).

**Comment by gschier** [comment]
That setting does not prevent the app from showing the message _after_ updating. It only prevents the message to notify you that there is a new release to install if you are not yet on the latest.

It has been requested to have a global setting to disable all notifications. Perhaps that would be a better solution?

**Comment by shroudedcode** [comment]
> It only prevents the message to notify you that there is a new release to install

Oh, gotcha.

> It has been requested to have a global setting to disable all notifications. Perhaps that would be a better solution?

Yeah, that would be great! I always dismiss Insomnia's notifications because they're quite distracting and I'm not interested in your paid offering at the moment. If I do want to find out about new features I can always manually look at the changelog.

Thanks for making an otherwise absolutely delightful REST client!

**Comment by filfreire** [comment]
Closing this one since. Folks should be able to disable notifications altogether in settings:
![Image](https://user-images.githubusercontent.com/11976836/184343912-1dfd69e2-7788-43f8-b201-6cdff505f71d.png)
![Image](https://user-images.githubusercontent.com/11976836/184343938-88a91d99-82b3-4973-8caa-47d51a544430.png)
