### ISSUE TITLE
[Question] Make requests without 'New Request'.

### ISSUE THREAD

**Issue by ravshansbox** [Kong/insomnia#1866]
**Is your feature request related to a problem? Please describe.**
What are the advantages of requiring user go through 'New Request', giving request a name, choosing METHOD that possibly can be set/changed later (when URL is not being asked!) to make a request? Wouldn't it be better to skip this step, eg: open app with default tab/panel where user can just select METHOD and type URL, optionally inputting body, etc and hit ENTER?

**Describe the solution you'd like**
User has to be able to work immediately without 'New Request' bureaucracy.

**Describe alternatives you've considered**
Remove redundant 'name' field for 'New Request' form or at least change it to URL. METHOD and URL should go in pair in HTTP.

**Additional context**
None.

**Comment by erohmensing** [comment]
+1, I always find this unintuitive. Usually when I'm creating a new request, I already have the URL copied and when the name input box comes up, find it strange, especially bc you have to choose the method

IMO it would be nicer to not have a form at all, + button would open a new request defaulted to GET and autofocus in on writing the name of it.

**Comment by ravshansbox** [comment]
Thank you, stale bot

**Comment by filfreire** [comment]
Hi @ravshansbox and @erohmensing thank you for reporting this, and apologies for not getting a reply in a LONG time.

We've been trying to improve this, and as of now (for example, version [2022.6.0-beta.1)](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.1), you should be able to quickly create a request without having to specify a lot of things and "going through more clicks".

On the plus button:
![Image](https://user-images.githubusercontent.com/11976836/184360946-f699b459-7d9e-47c0-82f0-ec65625671ba.png)

And on any folder's dropdown:
![Image](https://user-images.githubusercontent.com/11976836/184361030-4a1a7f1e-e80c-420c-b413-7acba5c6ad77.png)

And you should be able to use the keyboard shortcuts as well. Also the URL is focused when you switch to a new request.

Feel free to report other issues you come across!
