### ISSUE TITLE
[Feature Request] GraphQL Documentation for Union

### ISSUE THREAD

**Issue by jmiraglia-stuzo** [Kong/insomnia#1870]
**Is your feature request related to a problem? Please describe.**
The GraphQL documentation portion of Insomnia does not resolve `Union` data types. Drilling into one of these types always produces a `no description` value to be displayed.

**Describe the solution you'd like**
It would be great if when selecting a `Union` data type, any types that make up that union are presented in the same way that `Fields` is presented.

**Describe alternatives you've considered**
Right now there is no alternative solution except to look at the raw schema or use a different GraphQL client that parses this properly.

**Comment by elemanhillary-zz** [comment]
@jmiraglia-stuzo , it would be really nice if you provide me atleast the graphl api with some union data types so that i can work on this ASAP. Thanks

**Comment by jmiraglia-stuzo** [comment]
@elemanhillary For example, Artsy, contains a public API at https://metaphysics-production.artsy.net/. In this API there is a Query `artwork` returning type `Artwork`. `Artwork` contains `context: ArtworkContext`. `ArtworkContext` is a union. 
I've included screenshots of what is shown in Insomnia vs GraphiQL below as well:

![Open Commerce (Localhost) – Artsy 2020-01-09 08-50-19](https://user-images.githubusercontent.com/57498636/72073010-11f99b00-32bd-11ea-9cee-0f723662e366.png)

![GraphiQL 2020-01-09 08-49-34](https://user-images.githubusercontent.com/57498636/72072965-f8f0ea00-32bc-11ea-8ba7-117dc75769bf.png)

**Comment by elemanhillary-zz** [comment]
okay i will look on that, thanks

**Comment by elemanhillary-zz** [comment]
@jmiraglia-stuzo you can checkout the PR i have opened and give feedback
