### ISSUE TITLE
Sub-domain cookies not being sent when they should

### ISSUE THREAD

**Issue by mipper** [Kong/insomnia#1872]
Insomnia Version: 7.0.6
OS: Linux, Ubuntu Ubuntu 18.04.3 LTS

Cookie in the Cookie jar:
\_\_my_value\_\_=true; Domain=app-p2.domain.com; Path=/

Request URL:
https://us1a.app-p2.domain.com/service

Result:
The cookie is not included in the above request.

Expected Result:
The cookie should be included since the request is going to a sub-domain of the Domain specified by the cookie.

Additional notes:
If I go in and prepend a "*." to the cookie Domain the cookie is sent correctly.  The should not be necessary as cookies should already be sent to sub-domains.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

See section titled "Scope of cookies"

> For example, if Domain=mozilla.org is set, then cookies are included on subdomains like developer.mozilla.org.

And https://tools.ietf.org/html/rfc6265#section-5.1.3

> 5.1.3.  Domain Matching
> 
>    A string domain-matches a given domain string if at least one of the
>    following conditions hold:
> 
>    o  The domain string and the string are identical.  (Note that both
>       the domain string and the string will have been canonicalized to
>       lower case at this point.)
> 
>    o  All of the following conditions hold:
> 
>       *  The domain string is a suffix of the string.
> 
>       *  The last character of the string that is not included in the
>          domain string is a %x2E (".") character.
> 
>       *  The string is a host name (i.e., not an IP address).

Note that RFC-6265 replaced RFC-2109 which specified a leading . character to do this sub-domain matching.  Under RFC-6265 this is no longer required.

**Comment by gschier** [comment]
The Mozilla docs are referring to the `Set-Cookie` header value, not the value that ends up being stored in the cookie. If the `Set-Cookie` header contains `Domain=example.com` then the value stored in the cookie domain value will be `.example.com`. If no domain is set in the `Set-Cookie` header, the cookie will end up strictly set to the current domain of `example.com`

```js
document.cookie = "test=ExplicitDomain;domain=insomnia.rest";
document.cookie = "test=ImplicitDomain"
```

Will get:

![image](https://user-images.githubusercontent.com/587576/71730311-d455c780-2e0f-11ea-8957-0e4027b324d0.png)
