### ISSUE TITLE
[Feature] Ability to toggle multiple environments

### ISSUE THREAD

**Issue by dmlittle** [Kong/insomnia#283]
It'd be nice to have the ability to have multiple environments enabled in a certain workspace at any given time. This would allow you to have an environment and a private environment active at the same time to protect information that you might not want to accidentally expose.

For example, if you're dealing with an API you might have different Insomnia environments for different product environments (for example: local and production). This way I can have a production environment and a private production environment enabled at the same time. Optionally, you could also have protected environment keys that will not get exported when you export a certain environment.

Production Environment
```json
{
  "host": "https://api.service.com"
}
```
Private Production Environment
```json
{
  "API_KEY": "<SOME_SECRET_KEY>"
}
```

Local Environment
```json
{
  "host": "http://127.0.0.1:8443"
}
```
Private Production Environment
```json
{
  "API_KEY": "<SOME_OTHER_SECRET_KEY>"
}
```

**Comment by bboure** [comment]
+1 
I have the need to have something similar but I was thinking more in **nested environments** rather than enabling more than one at the same time.
Example: 
- I have dev and production sub environments.
- I want to test the API for different users.
- I create sub-sub-environments for each user under the already existing development/production and put (overwrite) there the api_key variable related to each user. 
Then I can easily switch user under a same env. 

The issue I see with multiple selected environments is to know what to do when you have conflicts (variables present in several selected environments). How do you resolve them?
Nested environments solves this issue by using variables by bubbling up from the selected env to the top.

**Comment by StanSvec** [comment]
Is this feature still planned to implement? I'd like to migrate from Postman in my current company, but difficult to do it without this functionality.

**Comment by iakko** [comment]
I really need this too, is there a plan for this feature?

**Comment by aytacworld** [comment]
I need this feature too, but I found a workaround for this problem
Insert all your variables inside Base Environment but add them by group then by environment. eg
```
{
  "API_Server": {
    "testing": {
      "api_server_url": "https://testing.website.com/api"
    },
    "staging": {
      "api_server_url": "https://staging.website.com/api"
    }
  },
  "User": {
    "admin": {
      "username": "Admin"
    },
    "moderator": {
      "username": "Mod"
    }
  }
}
```

Then create one Sub-Environment with variables to select per group which environment and the variables itself
```
{
  "API_Server_environment": "testing",
  "User_environment": "moderator",


  "API_Server": {
    "api_server_url": "{{ API_Server[API_Server_environment].api_server_url }}"
  },
  "User": {
    "username": "{{ User[User_environment].username }}"
  }
}
```

So you only have to change `"*_environment"` variables to use the environments you want.
```
  "API_Server_environment": "testing",
  "User_environment": "moderator",
```

**Comment by jostFT** [comment]
any updates on this?

**Comment by acomagu** [comment]
I think "extending other env" feature also works as solution of this problem(not implemented; the feature I want).

For example:

Production Environment:

```
{
  "host": "https://api.service.com"
}
```

Private Production Environment:

```
{
  ...{{ prod }} // Means extending the Production Environment
  "API_KEY": "<SOME_SECRET_KEY>"
}
```

Local Environment

```
{
  "host": "http://127.0.0.1:8443"
}
```

Private Local Environment

```
{
  ...{{ local }} // Means extending the Local Environment
  "API_KEY": "<SOME_OTHER_SECRET_KEY>"
}
```
