### ISSUE TITLE
[Question] Custom OAuth2 headers

### ISSUE THREAD

**Issue by robertburczak** [Kong/insomnia#401]
Hi,

Is there a possibility to add custom headers to OAuth2 Authorization tab?

**Comment by orclev** [comment]
I just opened a feature request similar to this (#419) would that feature meet your need, or are you looking for a way of sending the token that doesn't use the Authorization header?

**Comment by since78pl** [comment]
I am looking for possibility to send additional headers (name, value) as it is in Header tab for now, but in OAuth 2 tab.

**Comment by gschier** [comment]
@since78pl I'm curious, what kind of headers do you need to send with the OAuth requests?

**Comment by starJammer** [comment]
@gschier i'm guessing he's sending some custom headers that his authentication server listens to. Since the OAuth2 spec is pretty lax about additional things like this it isn't too surprising but I've not seen it done much.

**Comment by rupert654** [comment]
Can this please be looked at again?

Azure AD allows you to specify a "resource" header as part of the Access Token Request. This restricts the scope of your access token to the specific resources listed.

It doesn't seem to be possible to do this at the moment.

**Comment by JustinCoded** [comment]
Fitbit API also requires some credentials to be passed along in the Authorization header during exchange of auth code for access token, so this would be a great feature.

**Comment by p-m-j** [comment]
@DMarby accepting PRs for this or scheduling internally?

**Comment by DMarby** [comment]
@rustybox We'd be more then happy to accept a PR for it :)
