### ISSUE TITLE
[Feature Request] Command line API (import/export, send request)

### ISSUE THREAD

**Issue by multirealm** [Kong/insomnia#479]
- Insomnia Version: 5.8.2
- Operating System: Mac OS X

## Detaills
A command line API for import/export of workspaces or sending a request with a specific environment would be great.
Or is this even possible?
Thanks in advance!

**Comment by d-Pixie** [comment]
+1 for this. We are evaluating Insomnia in the context of using it as a headless test runner. The benefit would be that all developers can write their API specifications, regardless of desktop environment. Being able to use that resulting insomnia files with a CLI version on a docker container would be gold in this scenario 😄 

Anything planned? How hard would it be to factor out the UI and create a standalone core that could be run as a CLI client (I'm not above offering my time for that)?

**Comment by mgraham** [comment]
A headless CLI for running tests would be great.  To be useful to us, it would have to be capable of running inside of Travis.

**Comment by gschier** [comment]
This is something I've thought about for a while, but could never figure out a good way to interact with it. How would you prefer to reference the request? The only way I can see at the moment is by finding and using the unique ID that each one has. However, that seems like it would be extremely painful.

**Comment by mgraham** [comment]
I'll let you know once I play around with postman for awhile and figure out its pain points! :)

**Comment by gschier** [comment]
Oh ya, I forgot Postman had a CLI. Seems like a good place to start!

**Comment by gschier** [comment]
Report back with what you find 😄 👍

**Comment by gschier** [comment]
Hey @mgraham, did you get a chance to play around with the Postman CLI?

**Comment by msassak** [comment]
I want to add my support to adding a CLI for Insomnia to use it as a headless test runner. This is one of the reasons we pay for a Postman Pro account, but I would love to dump Postman Pro in favor of Insomnia.

**Comment by mgraham** [comment]
Yeah, Postman is so clunky!

One opportunity for Insomnia to improve upon Postman would be allowing referring to a specific  test case (and all of its template data, etc.) by a URL.

With Postman, we create a test case, and then in Pivotal Tracker stories and our Github PRs, we refer to the Postman test case and template by their _names_.  It makes for a very manual QA process.

Another great feature (and I realize this is a long shot) would be to integrate with some sort of click testing tool like Selenium; so you could do things like:
* run an API POST test to set up some data
* click in the UI of the app to see if the data is there.  Make changes
* run an API GET test to make sure the data is still there

I realize that click testing is *completely* out of scope for an API tool, but maybe there's some sort of fancy integration with a click testing tool that would make interleaved API tests and click tests possible.

**Comment by KimberleySDU** [comment]
why is this closed? I Googled here because this feature is what I am looking for. if it were around I'd be using it right now.

**Comment by mgraham** [comment]
Yeah, I'd say it's still an important issue.

**Comment by marmotz** [comment]
I think that you should start with a simple cli that just exports and imports Insomnia settings.
IMHO, it's "easy" to do and does not require discussion.

**Comment by citystar** [comment]
fyi, it looks that someone is taking action. https://www.npmjs.com/package/insomnia-cli

**Comment by mgraham** [comment]
I think it's still a valid long-term feature request

**Comment by cyberhck** [comment]
I wanted something which postman can't give and won't give.
- First I'd like a save location for individual collection, this way I have the ability to save my requests right on my git source control (not sure if it's already there)
- then I'd like to just run a cli `clinsomnia run ./collection` which would then run everything and execute tests

**Comment by alexus1024** [comment]
Currently use newman (postman cli) for executing api tests on CI. Store test suites in postman format.
It`s not comfortable - to update something in tests, I need to pull changes from VCS, import to postman, edit, export and then push.
It would be great if insomnia has similar feature but with direct load-save-to-file option, like other IDE-s.

**Comment by rmharrison** [comment]
@alexus1024 [dredd](https://github.com/apiaryio/dredd) is fantastic for running tests against the examples in a swagger/OAS contract (v2 `x-example`; v3 `examples`). It's _not_ a cli for a general purpose req/res tool (and is therefore not as customisable as newman), but for no-fuss testing with an existing contract, I consider it peerless.

**Comment by dgroomes** [comment]
Here is a Node.js script to export a workspace from Insomnia. It mostly boils down to this function https://github.com/dgroomes/nedb-playground/blob/0d20d10407408dfa6cd6a8d16ccd27ef65249a74/insomnia.js#L84

You use it with `npm install && node insomnia.js` and then it writes a valid Insomnia export file. (It hardcodes some things too). It was a good refresher for me for JavaScript (never used async/await) and to learn NeDB.

+1 for the CLI-based export/import feature request. If I had it then I think it would motivate me to export my 100+ requests that I've created over the years (the APIs for lots of DevOps tools and the APIs of our own system) and share them in version control for my colleagues! If I can get into a workflow of easily syncing my workspace with Git, that would be ideal. I see some really cool "Git syncing" and CLI functionality (`inso`) in the new Insomnia Designer! I would like to have that same functionality in Insomnia Core for exporting/importing (and maybe even diffing?) requests/workspaces.

I'm happy to try to restructure some things in Insomnia but didn't know where to start. Do you view that `inso` could evolve to interact with Insomnia Core and not just Designer?
