### ISSUE TITLE
[Feature Request] Expand/collapse All for tree view

### ISSUE THREAD

**Issue by multirealm** [Kong/insomnia#480]
- Insomnia Version: 5.8.2
- Operating System: Mac OS X

## Detaills
A possibility to expand and collapse all (shown) folders in the tree view with one click (or shortcut) would be very helpful. It could also be automatically applied after filtering, as currently sometimes only closed folders with hidden requests are shown. The "Expand all" feature could directly show all found requests. And "Collapse all" would close all folders again. Small buttons could be placed obove the tree view or also in the menu bar ("View"). Maybe it could be configurable in the preferences whether filtered folders are expanded directly.

**Comment by Kshmire** [comment]
I'm also interested in this feature.
I think in terms of usability it's better to show all the results when filtering. Even if they are in folders.

**Comment by enovision** [comment]
+1 for this feature. In my current project I would already clicked it at least hundreds of times. I really would love a collapse all and then easily pick the third node or so from a (large) JSON.

**Comment by bennettdams** [comment]
+1, could really use this, especially a default option to always expand/collapse the response.

**Comment by rcranney** [comment]
+1 for this feature....

**Comment by Brunohes** [comment]
+1 For this feature...

**Comment by Jaum97** [comment]
+1 Quality of life needed

**Comment by msphn** [comment]
+1 I would like as well!

**Comment by micha-hammer** [comment]
+1 This would be nice

**Comment by gschier** [comment]
Going to reopen this one based on demand
