### ISSUE TITLE
[Feature Request] Export individual request

### ISSUE THREAD

**Issue by wayneworkman** [Kong/insomnia#538]
I think it'd be helpful if I could right click one of my calls, and export it individually for one of my co-workers. With this, also the ability to import an individual call would be needed.

Thanks,
Wayne

**Comment by gschier** [comment]
That's a great idea. Would you be interested in submitting a PR to add that functionality? I be happy to help out with guidance if needed.

**Comment by wayneworkman** [comment]
@gschier I wouldn't know where to begin. I have not learned JS yet.

**Comment by gschier** [comment]
No worries. The reason I ask is that it's a fairly easy feature but I probably won't be able to get to it for a while. Would be perfect for a first-time contributor.

**Comment by Kshmire** [comment]
@gschier Hi, I've been thinking about the same functionality for some weeks. I know some JS but I'm no expert. Anyways, I'm up for it if you provide me some initial guidance. 

I owe you a debt of gratitude after you implemented Custom Timestamps after just one personal mail.

**Comment by gschier** [comment]
Hey @Kshmire. Sorry, I missed your comment. I would be happy to provide guidance. However, I have one question that I think should be discussed before moving forward on this.

## What do we do with variables when exporting a single request?

**Solution 1:**
The easiest solution would be to export the request as-is but that could cause problems. For example, the person who imports the request may not have the necessary environment variables defined. This would also cause problems if the request references data from another request (Response Body Tag).

**Solution 2:**
Another potential solution would be to render the entire request before exporting. This is what Insomnia does for code generation. This would make it work wherever it's imported no matter what.

Any feedback here would be appreciated.

**Comment by wayneworkman** [comment]
I vote for rendering fully. It's only a single request, the person
receiving the export can add their own environment variables after they
import.

**Comment by wayneworkman** [comment]
There's also the possibility of doing both solution 1 and 2. Check & see if the environment variables exist or not upon importing. If not, import the raw render. if so, use the env-vars that are available. Only use the env-vars if their names are an exact match.

**Comment by gschier** [comment]
Ya, I think fully rendered is the best and simplest option for now.

Your suggestion of exporting both at once is interesting. However, it's probably worth doing the simple one first. 

@Kshmire, you still interested in taking a crack at this?

**Comment by bernhardriegler** [comment]
If you could write up with some guidance, I will take a shot at this.

**Comment by jasonsemko** [comment]
@gschier still open for help on this? Can't let postman off the hook that easily!

**Comment by wayneworkman** [comment]
Have at it.

**Comment by gschier** [comment]
I'm still open to this if someone wants to pick it up 👌🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jasonsemko** [comment]
As an update I reached out to @gschier about a week ago via Twitter to get more context and thoughts on this solution so I can implement this in the simplest and most efficient way first time around. Have yet to hear back. @gschier is there a better way to contact you and discuss?  Only looking for a high level opinions/suggestions since you know the app better than anyone. Thanks

**Comment by mqueuester** [comment]
If it is possible to export  a request as a curl statement, I don't understand the complexity of exporting a request metadata to an output file. Here's a high level requirement; right click on the request and select export from the drop down menu. Query the user for the file name and location.

**Comment by LilSebastian5000** [comment]
Any update on this? I'm surprised this still isn't a feature yet. It's unfortunate that the only workaround is to create an entirely new workspace just to put one single request inside it

**Comment by tobiasr** [comment]
@gschier I'll have a go at this, if ok? I'll start by trying to complete solution 2, the simple, fully rendered version.
