### ISSUE TITLE
[Feature Request] Support multipart/mixed

### ISSUE THREAD

**Issue by rdehouss** [Kong/insomnia#599]
- Insomnia Version: 5.11.7
- Operating System: Linux

## Details

It would be awesome to be able to build more "complex" multipart requests.

A multipart/mixed is like this in curl

```
#/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

boundary="1c874d835a5b4376bd7b6ad60b54803a"

# generate the body
echo "--$boundary" > post
echo 'Content-Disposition: inline' >> post
echo 'Content-Type: application/json' >> post
echo '\r\n' >> post
cat ${DIR}/resources/some_json.json >> post
echo "\r\n--$boundary" >> post
echo 'Content-Disposition: attachment; filename="SampleVideo.mp4"' >> post
echo '\r\n' >> post
cat ${DIR}/resources/SampleVideo_1280x720_1mb.mp4 >> post
## final boundary uses two extra dashes
echo "\r\n--$boundary--" >> post

curl -H "Content-Type: multipart/mixed; boundary=$boundary" http://httpbin.org/post --data-binary @post

rm post
```

In the UI, it would allow to add "parts", specify the content-type and content-disposition of each (although, they are optional). In case of Content-Disposition: attachment, Insomnia would propose to attach a file (whatever the mimetype).
On send, Insomnia would generate its own boundary, set the right Content-Type (based on user input on the "general request", not the parts) (like multipart/mixed) and would send the parts in --data-binary (needs to be base64_encoded)

WDYT?

Thanks a lot already for the great product!

Cheers,

Raphaël

**Comment by gschier** [comment]
Hi @rdehouss, thanks for the comment 😄 

I'm not familiar with `multipart/mixed` but it seems like it's the exact same format as `multipart/form-data`, which Insomnia support. Is this assumption correct? 

If so, I think the only action items here are to have the ability to change the request Content-Type header from `multipart/form-data` to `multipart/mixed` as well as add the ability to specify custom headers per part. Does that sound correct?

Note: If you're not already aware, you can specify multipart data in Insomnia by selecting the Multipart Form body type

<img width="416" alt="image" src="https://user-images.githubusercontent.com/587576/32805107-5e1acc50-c980-11e7-8e90-e6ba4b82b50a.png">

**Comment by rdehouss** [comment]
Hi @gschier,

Yes, you're assumptions are correct.
And yes, I know I can already use Multipart Form which is indeed pretty close but which send using "form "field" name" (required), which is not correct in multipart/mixed.

If you need a beta tester, I'm available ;)

**Comment by rdehouss** [comment]
Up. This would still be a great improvement ;)

**Comment by andersonkxiass** [comment]
Any update about it ? Currently the only app that have this support it's Paw.

**Comment by rdehouss** [comment]
up
