### ISSUE TITLE
[Feature Request] Add timestamps to timeline

### ISSUE THREAD

**Issue by micgro42** [Kong/insomnia#618]
I searched and did not find a related issue.

- Insomnia Version: 5.11.7
- Operating System: Arch Linux

## Details
It would be super helpful if the timeline could show actual timestamps when each header/chunk was received.

### Use Case
We are trying to debug a request to the server for a dynamically generated pdf and more specifically when the download dialog in the browser opens. For this, it would be very helpful to see when the headers and the (first) chunks were received by the client.

**Comment by lifewcody** [comment]
I +1 this. Would be super helpful

**Comment by micgro42** [comment]
Would still be useful. 😉

**\*bump\***

**Comment by CodeZeno** [comment]
+1 would be very handy

**Comment by gschier** [comment]
Reopening this one

**Comment by gschier** [comment]
So the timeline entries are stored as keyed objects but displayed in a text editor instance. I just pushed a commit to start storing timestamps on each entry but I wasn't sure what the best way to display them would be. Perhaps a toggle to show them inline in the text editor, or show the timestamp when hovering each row. Thoughts?

**Comment by xernaj** [comment]
A toggle would be good

**Comment by Eandrju** [comment]
+1 I would kill right now for that feature
