### ISSUE TITLE
[Feature Request] Way to dump request with response

### ISSUE THREAD

**Issue by oliverjanik** [Kong/insomnia#650]
frequently when debugging someone else's API i need to dump the request and response and send it over email.

Can we have a dump/export as text button of both request and response together?

**Comment by gschier** [comment]
Interesting idea. You can sort of do this already by exporting the entire workspace as [HAR](http://www.softwareishard.com/blog/har-12-spec/) but it's not yet possible for individual requests.

Since HAR is already an export option, this issue will likely be closed by #538

**Comment by oliverjanik** [comment]
don't you dare stale bot!

**Comment by oliverjanik** [comment]
Not on my watch

**Comment by oliverjanik** [comment]
nope, is there a way to disable this pest?

**Comment by gschier** [comment]
Should remain open now!

**Comment by kiwiant** [comment]
Perhaps as a version 1.0 of this feature how about an option to export the response as a simple text file?

**Comment by bhabegger** [comment]
There is already an option to download the result to file when it gets to big. Making that button available even for smaller responses would be a first step :)

**Comment by elemanhillary** [comment]
> Interesting idea. You can sort of do this already by exporting the entire workspace as [HAR](http://www.softwareishard.com/blog/har-12-spec/) but it's not yet possible for individual requests.
> 
> Since HAR is already an export option, this issue will likely be closed by #538

Is this officially closed by #538

**Comment by gschier** [comment]
@bhabegger that same action is available under the preview tab dropdown
 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/587576/70644067-43287200-1c10-11ea-9120-ff2d565ca008.png">

**Comment by elemanhillary** [comment]
@gschier what's your conclusion about this

**Comment by gschier** [comment]
There's still no way in insomnia to dump both the request and response to a file. Maybe we could add another option to the preview actions. I think HAR could be a good format but I'm open to suggestions

**Comment by elemanhillary-zz** [comment]
yeah i totally see HAR as a solution, let me look at this

**Comment by elemanhillary-zz** [comment]
get me assigned to this @gschier so that it stays on my remainders
