### ISSUE TITLE
[Feature Request] Support file/folder backed workspaces

### ISSUE THREAD

**Issue by lldata** [Kong/insomnia#658]
Feature request:
As a developer I want to store my working REST examples along with my code / tests, 
so I always have a matching test environment for a given code version.

I order to do that I'd prefer if workspace/folder/requests was based on filesystem folders and files, rather than an internal database. I realize there is an export/import functionality, but developers generally forget to run it as workspaces are updated. I also realize that you have a cloud version, where workspaces can be shared. But that doesn't address the issue that the version should match with the code. Also I am sure that git is a better merge tool?
Having a file format, would also enable other tools to work with the files, which could be very powerful.

**Comment by gschier** [comment]
So, if I understand correctly, the structure of the data doesn't really matter. The core problem is that there is no good way to ensure the export is always up to date. 

I'm just going to write down some thoughts off the top of my head so feel free to comment on them.

## Solution 1 – 


## Solution 2 – Change Database Location

Insomnia's internal database is already persisted data to the filesystem in real-time. However, the location of those files is not configurable. It's possible to move those files to your Git folder and create a filesystem link to the original location, but this would have to be done for each member of your team.

**Comment by gschier** [comment]
Hi @lldata,

Can you explain the problem a bit more? Is the problem that developers forget to export workspaces after they change them or that they forget to import them after they checkout a new branch/commit?

**Comment by lldata** [comment]
As a developer I don't want to go through import/export at all. If you backed storage in a file format, rather than a database, there would be no import/export steps.

They just want to work on their code and the requests that match. When they are done they should be able to commit and have their work under version control together. And of course, if another developer works in the same workspace, their workspaces should be mergeable with as little fuzz as expected.

**Comment by schmidan** [comment]
i agree that this would be a highly appreciated feature for teams.
import/export on all changes is not really maintainable on faster development cycles and simultaneous api development.
@lldata explained it beautifully

**Comment by antarus** [comment]
i agree that this would be a highly appreciated feature for teams.

**Comment by tjventurini** [comment]
As a developer I would like to add an URL to my workspace from which the workspace gets updates from. This should be a json file, eg. in a GitHub project, that I can just reference.

What would you think about this approach? @gschier

**Comment by gschier** [comment]
@tjventurini that doesn't seem like it would solve the original problem since the user would still have to remember to export and store the file somewhere.

**Comment by tjventurini** [comment]
Thats true. Maybe an automatic export (like save to file) would be nice.

**Comment by leonidv** [comment]
Absolute useless tool (for me) without the possibility to save workspace on disk and share it through Git. So, SoapUI is still my choice.

**Comment by William-Jarden** [comment]
If I am not wrong, it seems Insomni couldn't work on a specific local work space. Isn't it?

**Comment by dimitropoulos** [comment]
@William-Jarden I don't understand your question: would you mind rephrasing?

To the rest of the people here, it seems like this can be closed because we have git sync now.  If I am mistaken please let me know and we can reopen.
