### ISSUE TITLE
[Feature] Multi-Window Support

### ISSUE THREAD

**Issue by njleonzhang** [Kong/insomnia#667]
can I open multi insomnia instance in mac for different workspace?

5.12.4.1752

**Comment by gschier** [comment]
Multiple windows are not currently supported at this time but hopefully this will be possible in the future.

As a (very hacky) workaround on Mac, you can duplicate the application with a different name, which will let you start two separate instances.

**Comment by njleonzhang** [comment]
@gschier tnx for response. wait for this feature, tnx.

**Comment by Fyb3roptik** [comment]
Any chance this gets bumped up in the todo list? This feature would be great!

**Comment by gschier** [comment]
Still on the list. There's actually a surprisingly large amount of work to do to make this work

**Comment by Fyb3roptik** [comment]
Please keep alive!

**Comment by nyel-dev** [comment]
still waiting ...

**Comment by alatella87** [comment]
+1

**Comment by jatinhariani** [comment]
+1

**Comment by Fyb3roptik** [comment]
@gschier Lets reactivate this please!

**Comment by dbodow** [comment]
+1

Or, if you find another good way to have a user work with multiple requests at once, that works too. I need to be able to see data from one endpoint and use it to play around with another endpoint side-by-side.

**Comment by labs-dlugo** [comment]
+1

**Comment by CallMeLaNN** [comment]
Insomnia is the best especially about the simplicity of the UI, plain json environment, E2EE and full GraphQL support.

I'm looking for multi-window support for a long time. This is the only missing feature in Insomnia and it is the only blocker for my team to get Teams plan and keep using multiple tools until now. Having many APIs for OIDC, GraphQL and REST from many backends require many open windows/tabs during API development of a feature.

I think the first step for Insomnia team is to describe the technical challenges other than creating electron new BrowserWindow, so we can look into this issue.

**Comment by raevilman** [comment]
On macOS, I am using below to launch an extra Insomnia instance. Works fine for me.

```
open -n -a "insomnia"
```

**Comment by sgarner** [comment]
I just wrote a feature request for the same thing in a help ticket and was directed to post here. I'm pleased to see this feature has already been discussed and appears to be quite popular, but troubled that it's apparently gone a long time with little progress!

I appreciate that this may be more work than it sounds - I'm imagining a bunch of things might need conceptual rewrites to allow concurrent operation - but it would clearly be a major step forward that would satisfy a lot of users, so I hope it can be given more priority.

Here's what I wrote:

> Could you please make it possible to open multiple windows for the application at once on macOS?
>
> I do contract work for multiple clients at a time and frequently need to context switch between projects. I like to organise the projects I'm working on into different Mac "Spaces" (desktops) to keep things tidy.
> 
> Insomnia already has excellent support for multiple workspaces. All that's missing is the ability to have different workspaces open concurrently in separate windows. This would help my productivity and happiness. For now I am stuck with one window that I have to move around all the time.
 
Thank you to the devs for your consideration. (Insomnia is awesome!)

----

> On macOS, I am using below to launch an extra Insomnia instance. Works fine for me.
> 
> ```
> open -n -a "insomnia"
> ```

I haven't tried this command exactly but I did try copying the whole Insomnia.app and opening it multiple times that way. This appeared to work okay until a reboot; when Insomnia re-opened, all of my requests were wiped. It looks like multiple copies of the app all write to a single set of database files in the `~/Library` directory - and that presumably leads to conflicts and data corruption. So I'd urge caution to anyone doing this, it may end in tears. See https://github.com/Kong/insomnia/issues/1763#issuecomment-565664651

**Comment by dimitropoulos** [comment]
@nijikokun I'm wondering if this would be in scope for the upcoming work on [spaces](https://github.com/Kong/insomnia/issues/3232).  If nothing else, I'd like us to keep this use-case in mind when we're building spaces so we make sure to pick a filesystem architecture that's not incompatible with multi-window.

**Comment by the-csaba** [comment]
bump message to keep this issue open
