### ISSUE TITLE
[Feature Request] CORS and preflight requests

### ISSUE THREAD

**Issue by BehindTheMath** [Kong/insomnia#687]
- Insomnia Version: 5.12.4
- Operating System: Windows 10 x64

## Details

Currently, Insomnia ignores any possible CORS issues, and always sends the request as is.

It would be nice to have the option to enable a strict CORS mode, where Insomnia would mirror the current behavior of browsers, by following the CORS spec and performing the following steps:

1) Check if the request requires a preflight request.
2) If yes, send a preflight request first.
3) If the server responds with an error, display that and abort the request.
4) If server responds with a preflight response, check the original request against the preflight response.
5) If it's valid, send the actual request and proceed as is done currently. (Also show the preflight request and response in the Timeline).
6) If it's not valid, display an error explaining why, and abort the request.

This would be valuable for testing and debugging CORS issues.

**Comment by BehindTheMath** [comment]
@insomnia I never received any response as to the viability of such a feature. Is this something you would consider adding to Insomnia?

**Comment by gschier** [comment]
Sorry I missed this one @BehindTheMath! 

If someone with knowledge of CORS wants to take this one on I'd be happy to help get it to a releasable state.

**Comment by Pettrie** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by BehindTheMath** [comment]
I think this is still a viable feature, and should not be marked stale.

**Comment by shutterstein** [comment]
I agree that this would be a viable feature.  Sure wish I had it right now as we are working with some of these issues.
