### ISSUE TITLE
Clicking on Search causes an Application Error

### ISSUE THREAD

**Issue by andrea-mauro** [Kong/insomnia#7199]
### Expected Behavior

When I click on the search input on the top left I expect the search input to open.

### Actual Behavior

The following application error shows up

<img width="813" alt="image" src="https://github.com/Kong/insomnia/assets/54074100/1a40bb0a-39a3-4a19-a59e-7ffabad78bc8">

### Reproduction Steps

1. Click the `Search` input field on the top left of the screen
2. An application Error shows up

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Note that this is not happening when using the keyboard shortcut (⌘P on Mac).

### Insomnia Version

develop branch

### What operating system are you using?

macOS

### Operating System Version

Mac OS Sonoma 14.3.1

### Installation method

running the latest develop version

**Comment by andrea-mauro** [comment]
I have a fix ready for this (see commit above). I'd be happy to publish a PR is this issue is confirmed.

**Comment by subnetmarco** [comment]
@andrea-mauro if you have a fix, I suggest to open the PR so we can take a look at what the fix looks like. It works in my tests, but you may be addressing some edge case.
