### ISSUE TITLE
[Feature Request] Pretty print JSONs while saving response to files

### ISSUE THREAD

**Issue by priyankgosalia** [Kong/insomnia#764]
[Feature Request] – Pretty print JSONs while saving response to files

- Insomnia Version: 5.14.7
- Operating System: Windows 7

## Details

Currently, if you save a JSON response to a file, the entire
JSON string gets saved as a single line in the file. Do you plan to
support pretty printing while saving to files ? Similar to the Visual Preview
feature but for files.

**Comment by gschier** [comment]
Since there are three (I think) places where responses can be saved, the best place to specify this would probably be a toggle in the global app preferences.

**Comment by geofmureithi** [comment]
@gschier I can help on this one as a first issue.

**Comment by gschier** [comment]
Awesome @geofmureithi! Let me know if you need some help or have questions :)

**Comment by evanslify** [comment]
@geofmureithi Are you still working on this issue?
