### ISSUE TITLE
[Feature Request] Search match count

### ISSUE THREAD

**Issue by evanzeller** [Kong/insomnia#776]
- Insomnia Version: 5.14.7
- Operating System: elementary OS 0.4.1 Loki (Ubuntu 16.04.2 LTS)

## Details

Insomnia has become my go to REST client aside from one feature, which is finding how many occurrences of a given value are in a response. It's a quick and dirty method of verification commonly used for the software I work with and for this purpose I usually keep open Insomnia and Postman. If a simple match count was added for ctrl-f searches I could completely eradicate Postman from my system. :smile:

**Comment by gschier** [comment]
Hmm, this seems like a fairly simple request. 

It doesn't look like Codemirror supports this feature but maybe we could add it ourselves: https://github.com/codemirror/CodeMirror/issues/3728

**Comment by Vyoam** [comment]
For note, Ace seems to support it. A bit weird how this request was outright closed in CodeMirror.
https://github.com/ajaxorg/ace/issues/3121
https://ace.c9.io

**Comment by alinoancea** [comment]
Hello @gschier,

Is this feature is still available/open for implementation? If so, I would like to give it a try.

Thanks.

**Comment by gschier** [comment]
Sorry for the delayed response but yes it is @alinoancea

**Comment by PCeja** [comment]
Hey is there anyone working on this? 
I use insomnia pretty often and I would like to work on it because that'd make a huge difference while using it.
