### ISSUE TITLE
[Bug Request] Fix Nunjucks Comments

### ISSUE THREAD

**Issue by tooolbox** [Kong/insomnia#842]
(Somewhere between a bug report and a feature request!)

- Insomnia Version: 5.14.3
- Operating System: OSX 10.13.3

## Details

Per #646 Insomnia uses [Nunjucks](https://mozilla.github.io/nunjucks/) as a templating language, which supports comments in the format of `{# comment #}` such as:
```nunjucks
{
    "heck": "yeah" {# great data #}
}
```

Currently Insomnia does *support* this technically, but when you complete typing one of these comments, it turns into a light blue clickable button thingy embedded in the text.  When you click it, it brings up a modal that has the title "Edit" but no body or other options.  There's no other way to edit the comment.

As long as I'm griping, the presence of one of these comments also spoils the otherwise pristine and gorgeous syntax highlighting of my JSON payload!  So they are a mixed blessing currently.

Thanks for an awesome REST client!

**Comment by gschier** [comment]
Thanks for posting this @tooolbox! The editing should be an easy fix but making the highlighting wor requires writing a custom JSON highlighter and linter (currently using the CodeMirror-provided one). Not impossible, but a lot more work.

**Comment by tooolbox** [comment]
Huh.  Yeah, I had a look at that parser and that looks rough, man.

...Just to throw it out there, what if you swapped any `/* ... */` patterns for `{# ... #}` before parsing with Nunjucks?  Then you could use JS block comments, and at least the syntax highlighting would work, even if the linter still complains.

Bit of a hack, so I'd understand any objections.

**Comment by gte451f** [comment]
+1 for the option to edit comments.  When working on APIs it's useful to temporarily omit some parts of the payload.

**Comment by maciek-d** [comment]
Any updates on this issue?

**Comment by eMerzh** [comment]
could we reopen this? i stumble upon this issue too!
and it would be a really appreciated feature!

**Comment by gschier** [comment]
Sorry! Not sure why Statebot closed this one
