### ISSUE TITLE
[Feature Request] GraphQL - Automatically generate leaf nodes 

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [Kong/insomnia#892]
- Insomnia Version: 5.15.0
- Operating System: Arch Linux

## Details

Hi there!

[Back then](https://github.com/getinsomnia/insomnia/issues/450) someone asked for a feature in GraphQL to automatically generate leaf nodes when opening the query brackets, but the request got stale and closed.

As of today, is this feature still hard to be implemented? Insomnia's GraphQL already have a good intellisence, so I'm guessing it has all information needed to automatically generate all leaf nodes when openning the query bracket. Like GraphiQL, this feature should be activated as needed.

It is easier to generate all leaf nodes and delete the unwanted ones than to write each required node.

Edit: Would be good an option to set the level of children to generate. If set to 1, then only the direct children will be generated. If set to 2, then the children's children will be generated as well, and so on. For me 1 level is good enough.

Best regards,
Rafael Pacheco.

**Comment by rafaelrenanpacheco** [comment]
![noooo](https://user-images.githubusercontent.com/12160864/57500438-d2a42600-72b9-11e9-889d-4278b60ec8df.gif)

**Comment by develohpanda** [comment]
Hahaaaa 😄 

Let me give this one a go. I've been working with GraphQL plenty (via GatsbyJS) but may still need some advice with this. Any suggestions?

**Comment by develohpanda** [comment]
Example of how GraphiQL achieves this - https://github.com/graphql/graphiql/blob/5b9012ea0e74452787f6c793d68aaa2cb915731b/src/utility/fillLeafs.js#L73-L104
