### ISSUE TITLE
[Feature Request] Improved autocomplete in GraphQL variables editor (fields of input types)

### ISSUE THREAD

**Issue by falkenhawk** [Kong/insomnia#902]
- Insomnia Version: 5.16.0
- Operating System: win10

an excerpt from graphql schema:
```
cards(filters: FilterInput): CardResults!
input FilterInput {
  where: [FilterWhereInput]
  eager: [FilterEagerInput]
  sort: [FilterSortInput]
  range: FilterRangeInput
}

```

sample query:
```
query cards($filters: FilterInput) {
  cards(filters: $filters) {
     id
  }
}
```

As discussed in #887 ,
it would be awesome to make the autocomplete in GraphQL variables editor work similar to Graphiql, when it comes to suggesting fields from inside input types.

![](https://user-images.githubusercontent.com/14310995/39305652-22671d9a-495e-11e8-85d3-f801b3090cfd.png)

Wrapping suggested field names with quotes and appending a colon+space would be also a nice addition:
![obraz](https://user-images.githubusercontent.com/14310995/39306213-cd754d5a-495f-11e8-8e7e-3b392cfb0dd6.png)
⬇️  
![obraz](https://user-images.githubusercontent.com/14310995/39306296-1659b830-4960-11e8-8e89-00e6ad44d67b.png)

**Comment by gschier** [comment]
Oh, this was done a while ago!

**Comment by martasd** [comment]
Are there any plans for implementing this feature in Insomnia?

**Comment by gschier** [comment]
Not sure why this got closed. No bandwidth to implement right away but could be a nice community addition

**Comment by tvvignesh** [comment]
Hey guys. This would be great to have. Can make our life a lot simpler. Currently, I have to end up either manually typing or copy pasting variables with complex object or array types. The main query/mutation editor autocomplete works great but variables and  input autocomplete doesn't exist sadly. Kindly repoen this.

Same as: 
https://github.com/Kong/insomnia/issues/887
https://github.com/Kong/insomnia/issues/2147

CC: @develohpanda @DMarby
