### ISSUE TITLE
[Feature Request] Allow multiple results for JSONPath in JSON bodies

### ISSUE THREAD

**Issue by whichken** [Kong/insomnia#944]
- Insomnia Version: 5.16.2
- Operating System: macOS

## Details

I make heavy use of chaining requests with template tags which is very powerful. However, I find it rather restrictive when working with JSON bodies in a POST request.

### Use case

I query a REST endpoint which returns an array of elements. In the response preview, I can use a JSONPath such as `$.data[*].id` to drill down to an array of id strings.

I would like to chain this to another POST request and provide this array as the JSON body. However, when I try to do so, the request fails to render with the following error: `Returned more than one result: $.data[*].id`

It would be great if JSON arrays could be rendered within JSON bodies.

**Comment by ignacio-chiazzo** [comment]
This is a nice feature!

**Comment by AndrewStickler** [comment]
I'd like to see this feature too. 
Use case:
Method1 returns an array of objects, each have a "type" and an "id" attribute.
Method2 accepts an array of ids.
I want to use a JSONPath filter on "type" to pass a subset of the ids from Method1's response to Method2.

e.g. 
Source data:
```json
{
  "nodes": [
    { "type" : "T1", "id": 27 },
    { "type" : "T2", "id": 28 },
    { "type" : "T1", "id": 29 }
  ]
}
````
the following filter 
```ts
$.nodes[?(@.type=="T1")].id 
```
should return an array of ids
```ts
[27, 29]
```

Please re-open this issue.
Thanks,
Andrew

**Comment by TravoNati** [comment]
bump

**Comment by tucosaurus** [comment]
Hey all, I would like to see this feature as well. Here's my use case.
I have an api whose request body needs a list of id's from an endpoint previously requested.

This is the request body structure.
```
{
    "items": ["93bef29c-e0c4-4428-bc96-6877b1430ba3"]
}
```

I get the list of item ids from an `/items` endpoint.

**Comment by renatojf** [comment]
Can this be reopened? This would be a great feature to have.

**Comment by nametable** [comment]
I would like this feature as well. The preview JSONPath seemed to show that I would get multiple values, but then I got the `Returned more than one result` error :cry: when using with Chaining

**Comment by highwaycat** [comment]
I'd like to join to the requester's list! It would be nice to support this feature.

**Comment by mzy1997** [comment]
I really need it!

**Comment by dimitropoulos** [comment]
Providing a mockbin.org link and clear steps to reproduce the behavior in question will help greatly in prioritizing this issue.

**Comment by NikkyAI** [comment]
another thing that could be useful is to generate a http request for each element.. there is enough API's like that sadly

**Comment by mtausig** [comment]
@dimitropoulos I'll try to give a concise explanation of the issue:

Assume there is an endpoint `/api/endpoint1` which returns the JSON-body

```JSON
{ "data": [
    {"id": 42, "name": "foo"},
    {"id": 123, "name": "bar"}
  ]
}
```

The goal is to call another endpoint `/api/endpoint2` with the body

```JSON
{ "data_ids": [42, 123]}
```

The value can easily be extracted using the JSONPath query `$.data[*].id`, but trying to use that in a chained request fails, as the following screenshot shows:

![image](https://user-images.githubusercontent.com/1511226/138055861-df0d6246-485a-493e-ae70-055aad889f3e.png)

**Comment by alexqhj** [comment]
This would be very useful. Scratched my head why my JSONPath syntax wasn't working.

**Comment by rpolnx** [comment]
Any updates?

**Comment by filfreire** [comment]
Hi folks! We merged @bbbco's PR which adds support for this. You should be able to use it in one of our upcoming releases, in this case 2022.7.0-beta.4
