### ISSUE TITLE
[Bug] Putting a Template Tag into GraphQL Query Variables JSON as a value sans quotes results in an error.

### ISSUE THREAD

**Issue by ylg** [Kong/insomnia#973]
Insomnia Version: 5.16.6 (5.16.6.2073)
Operating System: macOS 10.13.4 (17E202)

## Details

Setup an request as a GraphQL request and put a Template Tag in the Query Variables JSON as a direct property value, i.e., not wrapped in quotes.

For example:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/76547/41108502-ee9d8496-6a31-11e8-8dc1-a3eba76fa502.png">

The first property, "foo", with the quotes around the Template Tag is accepted by Insomnia. The second property "bar" is not, however the value must be sent as an integer not as a string and so the second form is needed.

_Side-note: A somewhat surprising UX side-effect of this is that clicking on a different request in the side bar and then back on the query with this problem shows the variables JSON as it was prior to making the change, i.e., invalid JSON is just thrown away if the user looks at another request._

**Comment by gschier** [comment]
Currently, the GraphQL editor requires it to have a valid query and variables section before saving. It's probably worth allowing invalid input to be saved, though.

**Comment by ylg** [comment]
Just to be clear, the example I gave and am interested is valid. In JSON, only strings are quoted, not integers, booleans, and so on.

**Comment by gschier** [comment]
Sorry, I should have clarified. It's not valid because of the way Insomnia does template variables. Your example is actually this, under the hood.

```json
{
	"foo": "{% now 'millis', '' %}",
	"bar": {% now 'millis', '' %}
}
```

**Comment by sylvainlegault** [comment]
Any resolution? we must be able to pass integer value as variables, even if they are from a template

**Comment by ylg** [comment]
This is still an issue as of 6.5.4.2876. Since you accepted it @gschier, might be good to block the stale bot with exemptLabels or some such.

**Comment by markhewett** [comment]
Any updated on this one, or any workaround to pull non-string values (number, array, etc.) from previous responses?

**Comment by zzFluke** [comment]
I've noticed same behavior using REST json payload. Template tags that are not wrapped in quotes, that must be rendered to any valid json value other than `STRING` reported by linter as a syntax error.

```
{
     "DestinationPort": {% prompt 'Destination Port', 'Enter Destination Port', '', '', false %}
}
```

Gives:
`Expecting 'STRING', '}', got 'undefined'`

**Comment by perplexedyawdie** [comment]
Any updates on this as yet? I'm getting a similar error message when trying to use a template tag with an environment variable

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by fabriziotrenti** [comment]
This problem is still present in version 2022.6.0
Has anyone been able to find a solution?

**Comment by davidegolzi** [comment]
i have the same problem trying to use a boolean variable, what's goning on this?

**Comment by raducrisan1** [comment]
I also have this problem. Is it such an edge case to use a computed timestamp in a GraphQL variable ? Do the maintainers even want us to use Insomnia for GraphQL projects ? I wonder why this hasn't been addressed for almost 5 years ...

[EDIT]: I looked for a while and seems that the problem is wider: with regards of GraphQL support there's no way of passing plugin results or even env variables to non-string variables. It looks to me like a stopper.
 
![image](https://user-images.githubusercontent.com/15193363/235297190-51bad7d7-9ca7-4e73-bf55-4b68c8a860b3.png)

**Comment by ihexxa** [comment]
This seems to be a similar issue with: https://github.com/Kong/insomnia/issues/1937

**Comment by notjaywu** [comment]
This issue should have been fixed already.

**Comment by notjaywu** [comment]
Close issue since it has been fixed already.
