### ISSUE TITLE
[Bug] Windows goes blank after receiving response in a random request

### ISSUE THREAD

**Issue by Navds** [Kong/insomnia#976]
[Bug]
- Insomnia Version: 5.16.6
- Operating System: Centos7

## Details
I'm running insomnia-5.16.6-x86_64.AppImage on Centos7 with Gnome Shell 3.14.4, Gtk+ Theme Zorba-Black.
When I get response for a request, all window content goes white leaving only the title bar. Restarting Insomnia restore gui elements, until the next request reponse.

Dependencies:

libcurl: 7.59.0
OpenSSL: 1.1.0h
zlib: 1.2.11
nghttp2: 1.31.1

**Comment by gschier** [comment]
Hmm, that's strange. Does it happen with any request, or a specific one?

Can you check View > Toggle DevTools > Console to see if there are any errors when it happens?

**Comment by Navds** [comment]
DevTools  was disconnected from the page. 
    One page is reloaded, DevTools will automatically reconnect.

**Comment by sc0ttwad3** [comment]
I am having the same issue.  To recreate: fresh install latest download for your OS (I'm running Windows 10 build 17692, Insomia v5.16.6) and step-by-step the tutorial.  When you get to the GitHub OAuth 2.0 page, and send the correctly configured request, the prompt for GitHub credentials sign-in is successful then all you get in return is a new blank window. 

Screenshot:

![insomnia-problem-white-screen](https://user-images.githubusercontent.com/1682691/41813652-20b343b6-7708-11e8-97f6-951451aaf237.jpg)

Not sure if having a working redirect_url on a server running at the time locally is required for the tutorial example, perhaps?

**Comment by gschier** [comment]
@sc0ttwad3 I'm pretty sure your problem is different. This issue is related to the app crashing, which results in the entire app becoming white. Your issue seems to be specific to the OAuth feature.

It's probably best to post a new (oauth-specific) issue outlining your problem.

**Comment by Navds** [comment]
Hi @gschier I'm not sure but I suspect it may be related to json parsing. These days, I'm working on  SOAP and never experienced the crash. Tried some REST API with json formatted response and it goes blank every time.

**Comment by gschier** [comment]
@Navds, do you have a public URL handy that I can test with?

**Comment by Navds** [comment]
This for example:
GET https://www.metaweather.com/api/location/search/?query=san

**Comment by sc0ttwad3** [comment]
@gschier Thx. I went ahead as directed and created #1000

**Comment by gschier** [comment]
Thanks @sc0ttwad3!

@Navds that URL seems to work for me (on Mac) 😕

**Comment by Navds** [comment]
insomnia is awesome on my mac or windows too. This bug concerns only the appimage on linux

**Comment by Jiig** [comment]
Any updates on this? Getting the same error with:

Insomnia Version: 6.3.2
Operating System: Centos7

**Comment by aindong** [comment]
I encountered the same problem today when I restored my MacBook pro 13inch on a new MacBook Pro 2015 15inch.

Scenario 1:
Open Insomnia using my old data and requests -> shows white screen only

Scenario 2:
Delete insomnia folder under `application support`
Open Insomnia (no data) -> shows the UI -> create a test get requests `https://google.com` -> click send -> white screen only

Scenario 3:
Delete insomnia folder
Uninstall insomnia
Open Insomnia (no data) -> shows the ui -> create a test get requests `https://google.com` -> click send -> white screen only


OS: High Sierra
Screen: 15inch
Resolution: 1920x1200

**Comment by aindong** [comment]
Finally, I was able to make it run by removing and reinstalling `zlib` on my mac using brew.

**Comment by gschier** [comment]
@aindong how on Earth did you figure that one out?

**Comment by bjorntj** [comment]
Any progress on this.. Having the same problem on my Linux computer using the AppImage version...

**Comment by sido420** [comment]
Same issue on my Mac 10.11.6 (El Capitan)

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by wongstein** [comment]
Piping in here again: Is this problem still reproducible with the latest Insomnia 2022.5.2?
