### ISSUE TITLE
[Bug] Swagger export not working with variables

### ISSUE THREAD

**Issue by Fyb3roptik** [Kong/insomnia#980]
- Insomnia Version: 5.16.1
- Operating System: macos

## Details

When exporting the json data to use in swagger, it does not change the variables to the actual values.

### Expected Results
http://myapi.com/v3/endpoint

### Actual Results
{{ base_url }}/{{ version }}/endpoint

This throws off any and all swagger generators

**Comment by gschier** [comment]
Does Swagger have it's own way of doing variables?

**Comment by gschier** [comment]
P.S. I know absolutely nothing about Swagger

**Comment by bobvanderlinden** [comment]
Hmm, it doesn't have variables in the same sense as Insomnia, but it does have path variables/parameters for instance. You can read more about path parameters here: https://swagger.io/docs/specification/2-0/describing-parameters/

It's a bit tricky, since some of the variables will be global (baseurl and maybe version of the API), but some are specific to the endpoint (clientid). I think you'd want to have the endpoint specific defined as path parameters, but have the global variables be resolved.

**Comment by jgy3183** [comment]
I was wondering if there was any updates on this.  I'm also having trouble getting an Insomnia API to import into swagger, due to in path parameters.

**Comment by thewheat** [comment]
I'd like to dig a bit more into this but I'm sure on the replication steps. Some questions I have are

1. Are we exporting as a regular Insomnia JSON file?
![image](https://user-images.githubusercontent.com/892961/96086463-f9c24680-0ef4-11eb-849c-20500f1a1391.png)
2. How is that file then imported to Swagger (I haven't had much exposure to it and the most references I've seen is https://editor.swagger.io/ but that doesn't recognize the Insonmia export file 
![image](https://user-images.githubusercontent.com/892961/96087170-072c0080-0ef6-11eb-9fe6-7abf4c21285c.png)

**Comment by Fyb3roptik** [comment]
I did the v4 JSON

**Comment by thewheat** [comment]
Thanks for the clarification @Fyb3roptik : how / where did you import into on the Swagger side of things?

**Comment by Fyb3roptik** [comment]
Honestly, this was from a while ago and im not sure this is still an issue. I am not on the project anymore so feel free to close this issue. Sorry to waste your time

**Comment by develohpanda** [comment]
I don't think this is anything to do with swagger in particular. Just looking at the initial report, this issue seems very closely related to https://github.com/Kong/insomnia/issues/2688
